#!/usr/bin/env python

import json
import os
import sys

from SCons.Script import ARGUMENTS, Default, Environment


def path_argument(name, default):
    return os.path.abspath(ARGUMENTS.pop(name, default))


repository_root = path_argument("repository_root", os.path.join("..", "..", "..", ".."))
source_root = path_argument("source_root", repository_root)
output_root = path_argument("output_root", os.path.join("..", "..", "build", "arena-agent"))
implementation_hash = ARGUMENTS.pop("implementation_hash", "unversioned")
build_id = ARGUMENTS.pop("build_id", "working-tree")
core_root = os.path.join(source_root, "native", "ptcg_core", "src")
challenge_root = os.path.join(source_root, "native", "challenge_core", "src")
common_root = os.path.join(repository_root, "native", "common")
json_root = os.path.join(
    repository_root, ".tools", "native", "nlohmann-json", "include")

env = Environment(ENV=os.environ)
env.Append(CPPPATH=[core_root, challenge_root, common_root, json_root])
env.Append(CPPDEFINES=[
    ("PTCG_AGENT_IMPLEMENTATION_HASH", '\\"' + implementation_hash + '\\"'),
    ("PTCG_AGENT_BUILD_ID", '\\"' + build_id.replace('"', '') + '\\"'),
])
if sys.platform == "win32":
    env.Append(CXXFLAGS=["/EHsc", "/std:c++17", "/O2", "/utf-8"])
else:
    env.Append(CXXFLAGS=["-std=c++17", "-O3", "-pthread"])
    env.Append(LINKFLAGS=["-pthread"])

with open(os.path.join(source_root, "native", "ptcg_core", "source_manifest.json"), encoding="utf-8") as handle:
    core_manifest = json.load(handle)
with open(os.path.join(source_root, "native", "challenge_core", "source_manifest.json"), encoding="utf-8") as handle:
    challenge_manifest = json.load(handle)

source_groups = [
    ("agent", ["ptcg_challenge_agent_main.cpp"]),
    ("ptcg_core", [os.path.join(core_root, name) for name in core_manifest["runtime"]]),
    ("challenge_core", [os.path.join(challenge_root, name) for name in challenge_manifest["runtime"]]),
]
objects = []
for group, sources in source_groups:
    for source in sources:
        objects.append(env.Object(
            os.path.join(
                output_root,
                "obj",
                group,
                os.path.splitext(os.path.basename(source))[0],
            ),
            source,
        )[0])
program = env.Program(os.path.join(output_root, "ptcg_challenge_agent"), source=objects)
env.NoCache(program)
Default(program)
