#!/usr/bin/env python

import os
import sys
import sysconfig
import json

from SCons.Script import ARGUMENTS, Default, Environment


def _path_argument(name, default):
    return os.path.abspath(ARGUMENTS.pop(name, default))


python_root = _path_argument("python_root", sys.prefix)
try:
    import pybind11

    default_pybind11_root = pybind11.get_include()
except ImportError:
    default_pybind11_root = os.path.join(
        python_root,
        "Lib" if sys.platform == "win32" else "lib",
        "site-packages",
        "pybind11",
        "include",
    )
pybind11_root = _path_argument("pybind11_root", default_pybind11_root)
output_root = _path_argument("output_root", "../../build/native")

env = Environment(ENV=os.environ)
repository_root = os.path.abspath(os.path.join("..", "..", "..", ".."))
core_source_root = os.path.join(repository_root, "native", "ptcg_core", "src")
challenge_source_root = os.path.join(
    repository_root, "native", "challenge_core", "src"
)
common_source_root = os.path.join(repository_root, "native", "common")
json_source_root = os.path.join(
    repository_root, ".tools", "native", "nlohmann-json", "include"
)
env.Append(
    CPPPATH=[
        "../src",
        core_source_root,
        challenge_source_root,
        common_source_root,
        json_source_root,
        sysconfig.get_paths()["include"],
        pybind11_root,
    ],
)
if sys.platform == "win32":
    env.Append(
        LIBPATH=[os.path.join(python_root, "libs")],
        LIBS=[f"python{sys.version_info.major}{sys.version_info.minor}"],
        CXXFLAGS=["/EHsc", "/std:c++17", "/O2", "/utf-8"],
    )
    extension_suffix = ".pyd"
else:
    env.Append(
        CXXFLAGS=["-std=c++17", "-O3", "-fPIC", "-pthread"],
        LINKFLAGS=["-pthread"],
    )
    extension_suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"

with open(
    os.path.join(repository_root, "native", "ptcg_core", "source_manifest.json"),
    encoding="utf-8",
) as handle:
    core_manifest = json.load(handle)
core_sources = [
    os.path.join(core_source_root, filename)
    for filename in core_manifest["runtime"]
]
core_objects = [
    env.Object(
        os.path.join("build", "ptcg_core", os.path.splitext(
            os.path.basename(source)
        )[0]),
        source,
    )[0]
    for source in core_sources
]
core_library = env.StaticLibrary(
    os.path.join(output_root, "lib", "ptcg_core_python"),
    source=core_objects,
)
env.NoCache(core_library)
env.Append(LIBS=[core_library])

with open(
    os.path.join(
        repository_root, "native", "challenge_core", "source_manifest.json"
    ),
    encoding="utf-8",
) as handle:
    challenge_manifest = json.load(handle)
challenge_sources = [
    os.path.join(challenge_source_root, name)
    for name in challenge_manifest["runtime"]
]
challenge_objects = [
    env.Object(
        os.path.join(
            "build",
            "challenge_core",
            os.path.splitext(os.path.basename(source))[0],
        ),
        source,
    )[0]
    for source in challenge_sources
]
challenge_library = env.StaticLibrary(
    os.path.join(output_root, "lib", "challenge_core_python"),
    source=challenge_objects,
)
env.NoCache(challenge_library)
env.Prepend(LIBS=[challenge_library])

binding_sources = [
    "ptcg_ai_core_module.cpp",
    "../src/ptcg_ai_core.cpp",
    "../src/ptcg_actor_v3.cpp",
    "../src/ptcg_challenge_arena.cpp",
    "../src/ptcg_challenge_arena_agent.cpp",
    "../src/ptcg_determinizer.cpp",
    "../src/ptcg_encoder_v3.cpp",
    "../src/ptcg_infoset.cpp",
    "../src/ptcg_search.cpp",
]
binding_objects = [
    env.SharedObject(
        os.path.join(
            "build",
            "bindings",
            os.path.splitext(os.path.basename(source))[0],
        ),
        source,
    )[0]
    for source in binding_sources
]

library = env.SharedLibrary(
    os.path.join(output_root, "ptcg_ai_core"),
    source=binding_objects,
    SHLIBPREFIX="",
    SHLIBSUFFIX=extension_suffix,
)
env.NoCache(library)
Default([core_library, challenge_library, library])
