"""Card definitions: colorless."""

CARDS = {'svf-farf': {'name': '大葱鸭',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 90,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '背来',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己牌库上方抽取2张卡牌。'},
                          {'name': '甩葱殴打', 'cost': ['Colorless'], 'damage': '30', 'text': ''}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'背来': {'effects': [{'effect_type': 'draw',
                                                           'params': {'amount': 2,
                                                                      'player': 'self'}}]},
                                       '甩葱殴打': {'effects': []}}}},
 'svf-hawl': {'name': '摔跤鹰人',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '展示姿态',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '选择自己弃牌区中最多2张基本能量，附着于1只备战宝可梦身上。'},
                          {'name': '挥落',
                           'cost': ['Colorless'],
                           'damage': '30+',
                           'text': '如果对手的战斗宝可梦为进化宝可梦的话，则追加造成30点伤害。'}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'展示姿态': {'effects': [{'effect_type': 'attach_from_discard',
                                                             'params': {'amount': 2,
                                                                        'energy_type': 'basic',
                                                                        'target': 'bench',
                                                                        'min_select': 0,
                                                                        'same_target': True,
                                                                        'select_source': True}}]},
                                       '挥落': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                                           'params': {'bonus': 30,
                                                                      'condition': 'opponent_active_evolved'}}]}}}},
 'svg-cast': {'name': '飘浮泡泡',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '双重抽取',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己的牌库上方抽取2张卡牌。'},
                          {'name': '暴风',
                           'cost': ['Colorless'],
                           'damage': '30',
                           'text': '选择附着于这只宝可梦身上的1个基本能量，转附于备战宝可梦身上。'}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'双重抽取': {'effects': [{'effect_type': 'draw',
                                                             'params': {'amount': 2}}]},
                                       '暴风': {'effects': [{'effect_type': 'energy_relocate',
                                                           'params': {'amount': 1,
                                                                      'from_self': True,
                                                                      'energy_type': 'basic_energy'}}]}}}},
 'svg-milt': {'name': '大奶罐',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 120,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '活泼冲撞',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '60+',
                           'text': '在这个回合，如果回复了这只宝可梦的HP的话，则追加造成90伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'attacks': {'活泼冲撞': {'effects': [{'effect_type': 'conditional_damage_heal',
                                                             'params': {'base': 60,
                                                                        'bonus': 90}}]}}}},
 'svg-swa': {'name': '青绵鸟',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 50,
             'types': ['Colorless'],
             'evolvesFrom': '',
             'attacks': [{'name': '连续旋转',
                          'cost': ['Colorless'],
                          'damage': '20×',
                          'text': '抛掷硬币直到出现反面，造成正面次数×20点伤害。'}],
             'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'连续旋转': {'effects': [{'effect_type': 'coin_flip_until_tails',
                                                            'params': {'per_head': 20}}]}}}},
 'svi-aipo': {'name': '长尾怪手',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 60,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '骗取',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己牌库上方抽取1张卡牌。'},
                          {'name': '掌击',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '20',
                           'text': ''}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'骗取': {'effects': [{'effect_type': 'draw',
                                                           'params': {'amount': 1,
                                                                      'player': 'self'}}]},
                                       '掌击': {'effects': []}}}},
 'svi-ambi': {'name': '双尾怪手',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 100,
              'types': ['Colorless'],
              'evolvesFrom': '长尾怪手',
              'attacks': [{'name': '招来',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己牌库上方抽取2张卡牌。'},
                          {'name': '长手抛掷',
                           'cost': ['Colorless', 'Colorless', 'Colorless'],
                           'damage': '20×',
                           'text': '造成自己手牌张数×20伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                                           'params': {'amount': 2,
                                                                      'player': 'self'}}]},
                                       '长手抛掷': {'effects': [{'effect_type': 'damage_per_hand_size',
                                                             'params': {'per': 20}}]}}}},
 'svi-flam': {'name': '缠红鹤',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 110,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '振翅', 'cost': ['Colorless'], 'damage': '30', 'text': ''},
                          {'name': '俯冲',
                           'cost': ['Colorless', 'Colorless', 'Colorless'],
                           'damage': '110',
                           'text': '给这只宝可梦也造成20伤害。'}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'振翅': {'effects': []},
                                       '俯冲': {'effects': [{'effect_type': 'damage_counter_self',
                                                           'params': {'amount': 20,
                                                                      'damage_kind': 'self_damage'}}]}}}},
 'svi-gree': {'name': '藏饱栗鼠',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 130,
              'types': ['Colorless'],
              'evolvesFrom': '贪心栗鼠',
              'attacks': [{'name': '招来',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己的牌库上方抽取2张卡牌。'},
                          {'name': '倾倒一空',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '60+',
                           'text': '将自己的手牌全部放于弃牌区。如果将5张以上放于弃牌区，则追加造成150点伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
              'convertedRetreatCost': 3,
              '_effects': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                                           'params': {'amount': 2,
                                                                      'player': 'self'}}]},
                                       '倾倒一空': {'effects': [{'effect_type': 'discard_hand_conditional_bonus',
                                                             'params': {'threshold': 5,
                                                                        'base_damage': 60,
                                                                        'bonus': 150}}]}}}},
 'svi-inde': {'name': '爱管侍',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 90,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '招来',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '从自己的牌库上方抽取2张卡牌。'},
                          {'name': '妙手强念',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '10×',
                           'text': '造成自己手牌张数×10点伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                                           'params': {'amount': 2,
                                                                      'player': 'self'}}]},
                                       '妙手强念': {'effects': [{'effect_type': 'damage_per_hand_size',
                                                             'params': {'per': 10}}]}}}},
 'svi-maus': {'name': '一家鼠ex',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1', 'ex'],
              'hp': 230,
              'types': ['Colorless'],
              'evolvesFrom': '一对鼠',
              'rules': ['宝可梦ex规则：当你的宝可梦ex被击倒时，对手获得2张奖赏卡。'],
              'abilities': [{'name': '团结一致',
                             'text': '当这只宝可梦在战斗场上受到对手宝可梦的招式的伤害时，将自己场上「一对鼠」和「一家鼠」的数量×3个伤害指示物，放置于使用了招式的宝可梦身上。',
                             'type': 'Ability'}],
              'attacks': [{'name': '贪婪门牙',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '120',
                           'text': '从自己牌库上方抽取2张卡牌。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': [],
              'convertedRetreatCost': 0,
              '_effects': {'abilities': {'团结一致': {'trigger': 'on_damaged',
                                                  'effects': [{'effect_type': 'reactive_thorns',
                                                               'params': {'filter_names': ['一对鼠',
                                                                                           '一家鼠ex',
                                                                                           '一家鼠'],
                                                                          'per_pokemon': 3}}]}},
                           'attacks': {'贪婪门牙': {'effects': [{'effect_type': 'draw',
                                                             'params': {'amount': 2,
                                                                        'player': 'self'}}]}}}},
 'svi-skwv': {'name': '贪心栗鼠',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 60,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '啃咬', 'cost': ['Colorless'], 'damage': '20', 'text': ''}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'啃咬': {'effects': []}}}},
 'svi-sqwk': {'name': '怒鹦哥',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '呼朋引伴',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '选择自己牌库中最多2张基础宝可梦，放于备战区。并重洗牌库。'},
                          {'name': '飞翔',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '60',
                           'text': '抛掷1次硬币如果为反面，则这个招式失败。如果为正面，则在下一个对手的回合，这只宝可梦不受到招式的伤害和效果影响。'}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'呼朋引伴': {'effects': [{'effect_type': 'search',
                                                             'params': {'from_zone': 'deck',
                                                                        'filter': 'basic_pokemon',
                                                                        'destination': 'bench',
                                                                        'reveal': True,
                                                                        'count': 2,
                                                                        'min_select': 0}}]},
                                       '飞翔': {'effects': [{'effect_type': 'coin_flip',
                                                           'params': {'on_heads': [{'effect_type': 'prevent_all',
                                                                                    'params': {}}],
                                                                      'on_tails': [{'effect_type': 'attack_fail',
                                                                                    'params': {}}]}}]}}}},
 'svi-stan': {'name': '惊角鹿',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 110,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '后踢', 'cost': ['Colorless'], 'damage': '20', 'text': ''},
                          {'name': '疯狂俯冲',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '30×',
                           'text': '造成对手战斗宝可梦身上附有的能量数量×30点伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'后踢': {'effects': []},
                                       '疯狂俯冲': {'effects': [{'effect_type': 'damage_per_energy',
                                                             'params': {'base': 0,
                                                                        'per_energy': 30,
                                                                        'count_from': 'opponent_active',
                                                                        'target': 'opponent_active'}}]}}}},
 'svi-tand': {'name': '一对鼠',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 40,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '紧贴', 'cost': ['Colorless'], 'damage': '10', 'text': ''},
                          {'name': '踢飞',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '20',
                           'text': ''}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'紧贴': {'effects': []}, '踢飞': {'effects': []}}}},
 'svl-chat': {'name': '聒噪鸟',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Colorless'],
              'evolvesFrom': '',
              'attacks': [{'name': '循环抽取',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '将自己的1张手牌放于弃牌区。若这样做，则从自己牌库上方抽取2张卡牌。'},
                          {'name': '振翅', 'cost': ['Colorless'], 'damage': '10', 'text': ''}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [{'type': 'Fighting', 'value': '-30'}],
              'retreatCost': [],
              'convertedRetreatCost': 0,
              '_effects': {'attacks': {'循环抽取': {'effects': [{'effect_type': 'discard_then_draw',
                                                             'params': {'discard_amount': 1,
                                                                        'draw_amount': 2}}]},
                                       '振翅': {'effects': []}}}}}
