"""Card definitions: darkness."""

CARDS = {'svd-absol': {'name': '阿勃梭鲁',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 100,
               'types': ['Darkness'],
               'attacks': [{'name': '漩涡灾祸',
                            'cost': ['Darkness'],
                            'damage': '10',
                            'text': '给对手的所有宝可梦，各造成10点伤害。[备战宝可梦不计算弱点、抗性。]'},
                           {'name': '深挖伤口',
                            'cost': ['Darkness', 'Colorless'],
                            'damage': '50+',
                            'text': '如果对手的战斗宝可梦身上放置有伤害指示物的话，则追加造成70点伤害。'}],
               'weaknesses': [],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'漩涡灾祸': {'effects': [{'effect_type': 'bench_damage',
                                                              'params': {'amount': 10,
                                                                         'count': 5,
                                                                         'player': 'opponent',
                                                                         'choose_targets': False}}]},
                                        '深挖伤口': {'effects': [{'effect_type': 'attack_damage_formula',
                                                              'params': {'base': 50,
                                                                         'condition_bonus': {'condition': 'opponent_active_damaged',
                                                                                             'bonus': 70,
                                                                                             'consume': False}}}]}}}},
 'svd-dark-patch': {'name': '暗黑补丁',
                    'supertype': 'Trainer',
                    'subtypes': ['Item'],
                    'rules': ['选择自己弃牌区中的1张「基本恶能量」，附着于备战区的恶宝可梦身上。'],
                    'trainer_type': 'Item',
                    '_effects': {'trainer_effect': {'effect_type': 'attach_from_discard',
                                                    'params': {'amount': 1,
                                                               'energy_type': 'basic_darkness',
                                                               'target': 'bench',
                                                               'target_pokemon_type': 'Darkness'}}}},
 'svd-darkrai': {'name': '达克莱伊',
                 'supertype': 'Pokémon',
                 'subtypes': ['Basic'],
                 'hp': 120,
                 'types': ['Darkness'],
                 'attacks': [{'name': '恶梦',
                              'cost': ['Darkness', 'Colorless'],
                              'damage': '30',
                              'text': '使对手的战斗宝可梦陷入睡眠状态。'},
                             {'name': '漆黑之刃',
                              'cost': ['Darkness', 'Darkness', 'Colorless'],
                              'damage': '130',
                              'text': '在下一个自己的回合，这只宝可梦无法使用招式。'}],
                 'weaknesses': [],
                 'resistances': [],
                 'retreatCost': ['Colorless', 'Colorless'],
                 'convertedRetreatCost': 2,
                 '_effects': {'attacks': {'恶梦': {'effects': [{'effect_type': 'status',
                                                              'params': {'status': 'asleep',
                                                                         'target': 'opponent_active'}}]},
                                          '漆黑之刃': {'effects': [{'effect_type': 'self_attack_lock',
                                                                'params': {'attack_name': '漆黑之刃',
                                                                           'scope': 'all'}}]}}}},
 'svd-dodrio': {'name': '嘟嘟利',
                'supertype': 'Pokémon',
                'subtypes': ['Stage 1'],
                'hp': 100,
                'types': ['Colorless'],
                'evolvesFrom': '嘟嘟',
                'abilities': [{'name': '暴走抽取',
                               'text': '在自己的回合可以使用1次。给这只宝可梦身上放置1个伤害指示物。然后，从自己牌库上方抽取1张卡牌。',
                               'type': 'Ability'}],
                'attacks': [{'name': '愤怒之喙',
                             'cost': ['Colorless'],
                             'damage': '10+',
                             'text': '追加造成这只宝可梦身上放置的伤害指示物数量×30伤害。'}],
                'weaknesses': [],
                'resistances': [],
                'retreatCost': ['Colorless'],
                'convertedRetreatCost': 1,
                '_effects': {'abilities': {'暴走抽取': {'trigger': 'on_turn',
                                                    'effects': [{'effect_type': 'damage_counter_self',
                                                                 'params': {'amount': 10}},
                                                                {'effect_type': 'draw',
                                                                 'params': {'amount': 1,
                                                                            'player': 'self'}}]}},
                             'attacks': {'愤怒之喙': {'effects': [{'effect_type': 'attack_damage_formula',
                                                               'params': {'base': 10,
                                                                          'per_self_damage_counter': 30}}]}}}},
 'svd-doduo': {'name': '嘟嘟',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 70,
               'types': ['Colorless'],
               'evolvesTo': ['嘟嘟利'],
               'attacks': [{'name': '突击',
                            'cost': ['Colorless'],
                            'damage': '30',
                            'text': '给这只宝可梦也造成10伤害。'}],
               'weaknesses': [],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'突击': {'effects': [{'effect_type': 'damage_counter_self',
                                                            'params': {'amount': 10,
                                                                       'damage_kind': 'self_damage'}}]}}}},
 'svd-hard-belt': {'name': '坚硬束带',
                   'supertype': 'Trainer',
                   'subtypes': ['Tool'],
                   'rules': ['身上放有这张卡牌的1阶进化宝可梦，受到对手宝可梦的招式的伤害「-30」。'],
                   'trainer_type': 'Tool',
                   '_effects': {'trainer_effect': {'effect_type': 'tool',
                                                   'params': {'effect': 'damage_reduction_stage1',
                                                              'amount': 30}}}},
 'svd-mabosstiff-ex': {'name': '獒教父ex',
                       'supertype': 'Pokémon',
                       'subtypes': ['Stage 1', 'ex'],
                       'hp': 260,
                       'types': ['Darkness'],
                       'evolvesFrom': '偶叫獒',
                       'attacks': [{'name': '恫吓',
                                    'cost': ['Colorless', 'Colorless'],
                                    'damage': '30',
                                    'text': '在下一个对手的回合，受到这个招式影响的宝可梦所使用招式的伤害「-50」。'},
                                   {'name': '自尊獠牙',
                                    'cost': ['Darkness', 'Colorless', 'Colorless'],
                                    'damage': '100+',
                                    'text': '如果自己的备战宝可梦身上放置有伤害指示物的话，则追加造成120伤害。'}],
                       'weaknesses': [],
                       'resistances': [],
                       'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
                       'convertedRetreatCost': 3,
                       '_effects': {'attacks': {'恫吓': {'effects': [{'effect_type': 'apply_outgoing_damage_reduction',
                                                                    'params': {'amount': 50,
                                                                               'target': 'opponent_active'}}]},
                                                '自尊獠牙': {'effects': [{'effect_type': 'attack_damage_formula',
                                                                      'params': {'base': 100,
                                                                                 'condition_bonus': {'condition': 'own_bench_damaged',
                                                                                                     'bonus': 120,
                                                                                                     'consume': False}}}]}}}},
 'svd-maschiff': {'name': '偶叫獒',
                  'supertype': 'Pokémon',
                  'subtypes': ['Basic'],
                  'hp': 70,
                  'types': ['Darkness'],
                  'evolvesTo': ['獒教父ex'],
                  'attacks': [{'name': '踢飞',
                               'cost': ['Colorless', 'Colorless'],
                               'damage': '20',
                               'text': ''},
                              {'name': '锐利之牙',
                               'cost': ['Darkness', 'Colorless', 'Colorless'],
                               'damage': '50',
                               'text': ''}],
                  'weaknesses': [],
                  'resistances': [],
                  'retreatCost': ['Colorless', 'Colorless'],
                  'convertedRetreatCost': 2,
                  '_effects': {'attacks': {'踢飞': {'effects': []}, '锐利之牙': {'effects': []}}}},
 'svd-morpeko': {'name': '莫鲁贝可',
                 'supertype': 'Pokémon',
                 'subtypes': ['Basic'],
                 'hp': 80,
                 'types': ['Darkness'],
                 'attacks': [{'name': '捡食',
                              'cost': ['Colorless'],
                              'damage': '0',
                              'text': '选择自己弃牌区中的1张物品，在给对手看过之后，加入手牌。'},
                             {'name': '空腹撞击',
                              'cost': ['Darkness'],
                              'damage': '20+',
                              'text': '如果自己没有手牌的话，则追加造成90点伤害。'}],
                 'weaknesses': [],
                 'resistances': [],
                 'retreatCost': ['Colorless'],
                 'convertedRetreatCost': 1,
                 '_effects': {'attacks': {'捡食': {'effects': [{'effect_type': 'search',
                                                              'params': {'from_zone': 'discard',
                                                                         'filter': 'item',
                                                                         'destination': 'hand',
                                                                         'reveal': True,
                                                                         'count': 1}}]},
                                          '空腹撞击': {'effects': [{'effect_type': 'attack_damage_formula',
                                                                'params': {'base': 20,
                                                                           'condition_bonus': {'condition': 'own_hand_empty',
                                                                                               'bonus': 90,
                                                                                               'consume': False}}}]}}}},
 'svd-seviper': {'name': '饭匙蛇',
                 'supertype': 'Pokémon',
                 'subtypes': ['Basic'],
                 'hp': 110,
                 'types': ['Darkness'],
                 'attacks': [{'name': '锐利之牙', 'cost': ['Colorless'], 'damage': '20', 'text': ''},
                             {'name': '挥落',
                              'cost': ['Darkness', 'Colorless'],
                              'damage': '50+',
                              'text': '如果对手的战斗宝可梦为进化宝可梦的话，则追加造成50伤害。'}],
                 'weaknesses': [],
                 'resistances': [],
                 'retreatCost': ['Colorless'],
                 'convertedRetreatCost': 1,
                 '_effects': {'attacks': {'锐利之牙': {'effects': []},
                                          '挥落': {'effects': [{'effect_type': 'attack_damage_formula',
                                                              'params': {'base': 50,
                                                                         'condition_bonus': {'condition': 'opponent_active_evolved',
                                                                                             'bonus': 50,
                                                                                             'consume': False}}}]}}}}}
