"""Card definitions: dragon."""

CARDS = {'svg-alt': {'name': '七夕青鸟ex',
             'supertype': 'Pokémon',
             'subtypes': ['Stage 1', 'ex'],
             'hp': 260,
             'types': ['Dragon'],
             'evolvesFrom': '青绵鸟',
             'rules': ['宝可梦ex规则：当你的宝可梦ex被击倒时，对手获得2张奖赏卡。'],
             'abilities': [{'name': '哼唱治愈',
                            'text': '在自己的回合可以使用1次。将自己所有宝可梦的HP，各回复「20」。',
                            'type': 'Ability'}],
             'attacks': [{'name': '光之波动',
                          'cost': ['Water', 'Metal'],
                          'damage': '140',
                          'text': '在下一个对手的回合，这只宝可梦不受到对手宝可梦所使用招式的效果影响。'}],
             'weaknesses': [],
             'resistances': [],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'abilities': {'哼唱治愈': {'trigger': 'on_turn',
                                                 'effects': [{'effect_type': 'heal_all',
                                                              'params': {'amount': 20}}]}},
                          'attacks': {'光之波动': {'effects': [{'effect_type': 'prevent_effects',
                                                            'params': {}}]}}}},
 'svg-dram': {'name': '老翁龙',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 120,
              'types': ['Dragon'],
              'evolvesFrom': '',
              'attacks': [{'name': '逆鳞',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '60+',
                           'text': '追加造成这只宝可梦身上放置的伤害指示物数量×10伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'attacks': {'逆鳞': {'effects': [{'effect_type': 'damage_per_self_damage',
                                                           'params': {'base': 60,
                                                                      'per_counter': 10}}]}}}},
 'svg-tatsu': {'name': '米立龙',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 70,
               'types': ['Dragon'],
               'evolvesFrom': '',
               'attacks': [{'name': '水枪', 'cost': ['Water'], 'damage': '20', 'text': ''},
                           {'name': '生存战略',
                            'cost': ['Colorless', 'Colorless'],
                            'damage': '0',
                            'text': '选择自己牌库中任意卡牌最多2张，加入手牌。并重洗牌库。若希望，可将这只宝可梦与备战宝可梦互换。'}],
               'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'水枪': {'effects': []},
                                        '生存战略': {'effects': [{'effect_type': 'search_any_and_switch',
                                                              'params': {'count': 2,
                                                                         'min_select': 0,
                                                                         'switch_optional': True,
                                                                         'source_slot': 'active'}}]}}}}}
