"""Card definitions: fighting."""

CARDS = {'svf-klea': {'name': '劈斧螳螂',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 140,
              'types': ['Fighting'],
              'evolvesFrom': '飞天螳螂',
              'attacks': [{'name': '大树切割',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '0',
                           'text': '抛掷2次硬币，如果全部都是正面，则使对手的战斗宝可梦昏厥。'},
                          {'name': '暴走冲撞',
                           'cost': ['Fighting', 'Fighting'],
                           'damage': '120',
                           'text': '给这只宝可梦也造成30点伤害。'}],
              'weaknesses': [{'type': 'Psychic', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'attacks': {'大树切割': {'effects': [{'effect_type': 'coin_flip_double_ko',
                                                             'params': {}}]},
                                       '暴走冲撞': {'effects': [{'effect_type': 'damage_counter_self',
                                                             'params': {'amount': 30,
                                                                        'damage_kind': 'self_damage'}}]}}}},
 'svf-luca': {'name': '路卡利欧',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 120,
              'types': ['Fighting'],
              'evolvesFrom': '利欧路',
              'abilities': [{'name': '旺盛斗气',
                             'text': '在自己的回合可以使用1次。给这只宝可梦身上放置2个伤害指示物。然后，选择自己牌库中的1张斗能量卡，附着于这只宝可梦身上。并重洗牌库。',
                             'type': 'Ability'}],
              'attacks': [{'name': '连续波导弹',
                           'cost': ['Fighting', 'Fighting'],
                           'damage': '10+',
                           'text': '将附着于这只宝可梦身上的斗能量全部放于弃牌区，追加造成其张数×60点伤害。'}],
              'weaknesses': [{'type': 'Psychic', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'abilities': {'旺盛斗气': {'trigger': '',
                                                  'effects': [{'effect_type': 'damage_counter_self',
                                                               'params': {'amount': 20}},
                                                              {'effect_type': 'energy_attach',
                                                               'params': {'amount': 1,
                                                                          'from_zone': 'deck',
                                                                          'filter': 'fighting',
                                                                          'to': 'self'}}]}},
                           'attacks': {'连续波导弹': {'effects': [{'effect_type': 'discard_fighting_energy_damage',
                                                              'params': {'base': 10,
                                                                         'per_energy': 60}}]}}}},
 'svf-pass': {'name': '投掷猴',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 110,
              'types': ['Fighting'],
              'evolvesFrom': '',
              'attacks': [{'name': '辅助传递',
                           'cost': ['Fighting', 'Fighting'],
                           'damage': '70',
                           'text': '选择这只宝可梦身上附着的1个能量，转附于备战宝可梦身上。'}],
              'weaknesses': [{'type': 'Psychic', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'辅助传递': {'effects': [{'effect_type': 'energy_relocate',
                                                             'params': {'amount': 1,
                                                                        'from_self': True}}]}}}},
 'svf-rio': {'name': '利欧路',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 70,
             'types': ['Fighting'],
             'evolvesFrom': '',
             'attacks': [{'name': '重拳', 'cost': ['Fighting'], 'damage': '10', 'text': ''},
                         {'name': '突击',
                          'cost': ['Fighting', 'Colorless'],
                          'damage': '50',
                          'text': '给这只宝可梦也造成20点伤害。'}],
             'weaknesses': [{'type': 'Psychic', 'value': '×2'}],
             'resistances': [],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'重拳': {'effects': []},
                                      '突击': {'effects': [{'effect_type': 'damage_counter_self',
                                                          'params': {'amount': 20,
                                                                     'damage_kind': 'self_damage'}}]}}}},
 'svf-terr': {'name': '代拉基翁',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 130,
              'types': ['Fighting'],
              'evolvesFrom': '',
              'attacks': [{'name': '岩窟冲撞',
                           'cost': ['Fighting', 'Fighting', 'Colorless'],
                           'damage': '120',
                           'text': '在下一个对手的回合，这只宝可梦不会受到招式的伤害。在上一个自己的回合，如果自己的宝可梦使用了「岩窟冲撞」的话，则无法使用这个招式。'}],
              'weaknesses': [{'type': 'Grass', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
              'convertedRetreatCost': 3,
              '_effects': {'attacks': {'岩窟冲撞': {'effects': [{'effect_type': 'prevent_damage',
                                                             'params': {}},
                                                            {'effect_type': 'self_attack_lock',
                                                             'params': {'attack_name': '岩窟冲撞',
                                                                        'scope': 'player'}}]}}}}}
