"""Card definitions: grass."""

CARDS = {'svf-scyt': {'name': '飞天螳螂',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 90,
              'types': ['Grass'],
              'evolvesFrom': '',
              'attacks': [{'name': '高速镰刀', 'cost': ['Colorless'], 'damage': '20', 'text': ''}],
              'weaknesses': [{'type': 'Fire', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'高速镰刀': {'effects': []}}}},
 'svg2-brel': {'name': '斗笠菇',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 1'],
               'hp': 110,
               'types': ['Grass'],
               'evolvesFrom': '蘑蘑菇',
               'attacks': [{'name': '音速直击', 'cost': ['Grass'], 'damage': '60', 'text': ''}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'音速直击': {'effects': []}}}},
 'svg2-grot': {'name': '树林龟',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 1'],
               'hp': 100,
               'types': ['Grass'],
               'evolvesFrom': '草苗龟',
               'abilities': [{'name': '日光甲壳',
                              'text': '在自己的回合可以使用1次。选择自己牌库中的1张G宝可梦，在给对手看过之后，加入手牌。并重洗牌库。',
                              'type': 'Ability'}],
               'attacks': [{'name': '飞叶快刀',
                            'cost': ['Grass', 'Colorless', 'Colorless'],
                            'damage': '50',
                            'text': ''}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
               'convertedRetreatCost': 3,
               '_effects': {'abilities': {'日光甲壳': {'trigger': 'on_turn',
                                                   'effects': [{'effect_type': 'search',
                                                                'params': {'from_zone': 'deck',
                                                                           'filter': 'grass_pokemon',
                                                                           'destination': 'hand',
                                                                           'reveal': True,
                                                                           'count': 1}}]}},
                            'attacks': {'飞叶快刀': {'effects': []}}}},
 'svg2-shro': {'name': '蘑蘑菇',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 60,
               'types': ['Grass'],
               'evolvesFrom': '',
               'attacks': [{'name': '吸取',
                            'cost': ['Grass'],
                            'damage': '10',
                            'text': '回复这只宝可梦「10」HP。'}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'吸取': {'effects': [{'effect_type': 'damage_and_self_heal',
                                                            'params': {'damage': 10,
                                                                       'heal': 10}}]}}}},
 'svg2-tort': {'name': '土台龟',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 2'],
               'hp': 190,
               'types': ['Grass'],
               'evolvesFrom': '树林龟',
               'attacks': [{'name': '进化压制',
                            'cost': ['Grass', 'Colorless'],
                            'damage': '50×',
                            'text': '造成自己场上进化宝可梦数量×50点伤害。'},
                           {'name': '头突',
                            'cost': ['Grass', 'Colorless', 'Colorless', 'Colorless'],
                            'damage': '160',
                            'text': ''}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless', 'Colorless', 'Colorless'],
               'convertedRetreatCost': 4,
               '_effects': {'attacks': {'进化压制': {'effects': [{'effect_type': 'damage_per_evolved',
                                                              'params': {'per_evolved': 50}}]},
                                        '头突': {'effects': []}}}},
 'svg2-turt': {'name': '草苗龟',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 80,
               'types': ['Grass'],
               'evolvesFrom': '',
               'attacks': [{'name': '咬住', 'cost': ['Grass'], 'damage': '10', 'text': ''},
                           {'name': '鲁莽头击',
                            'cost': ['Grass', 'Colorless'],
                            'damage': '20',
                            'text': ''}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless'],
               'convertedRetreatCost': 2,
               '_effects': {'attacks': {'咬住': {'effects': []}, '鲁莽头击': {'effects': []}}}},
 'svg2-zaru': {'name': '萨戮德',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 130,
               'types': ['Grass'],
               'evolvesFrom': '',
               'attacks': [{'name': '唤群之歌',
                            'cost': ['Grass'],
                            'damage': '0',
                            'text': '选择自己牌库中的1张G宝可梦，在给对手看过之后，加入手牌。并重洗牌库。如果是后攻玩家的最初回合的话，则可加入手牌的G宝可梦的张数变为最多3张。'},
                           {'name': '反复鞭挞',
                            'cost': ['Colorless', 'Colorless', 'Colorless'],
                            'damage': '60+',
                            'text': '追加造成这只宝可梦身上附有的G能量数量×20点伤害。'}],
               'weaknesses': [{'type': 'Fire', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless'],
               'convertedRetreatCost': 2,
               '_effects': {'attacks': {'唤群之歌': {'effects': [{'effect_type': 'conditional_search_extra',
                                                              'params': {'filter': 'grass_pokemon',
                                                                         'max_count': 3,
                                                                         'default_count': 1}}]},
                                        '反复鞭挞': {'effects': [{'effect_type': 'damage_per_self_energy_type',
                                                              'params': {'base': 60,
                                                                         'per_energy': 20,
                                                                         'energy_type': 'Grass'}}]}}}}}
