"""Card definitions: psychic."""

CARDS = {'sv1-104': {'name': '墓仔狗',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 70,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '啃咬', 'cost': ['Psychic'], 'damage': '10', 'text': ''},
                         {'name': '幽魂射击',
                          'cost': ['Psychic', 'Colorless'],
                          'damage': '20',
                          'text': ''}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless', 'Colorless'],
             'convertedRetreatCost': 2,
             '_effects': {'attacks': {'啃咬': {'effects': []}, '幽魂射击': {'effects': []}}}},
 'sv1-106': {'name': '墓扬犬',
             'supertype': 'Pokémon',
             'subtypes': ['Stage 1'],
             'hp': 140,
             'types': ['Psychic'],
             'evolvesFrom': '墓仔狗',
             'attacks': [{'name': '扫墓',
                          'cost': ['Psychic', 'Psychic'],
                          'damage': '80+',
                          'text': '追加造成自己弃牌区中超宝可梦的张数×10伤害。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
             'convertedRetreatCost': 3,
             '_effects': {'attacks': {'扫墓': {'effects': [{'effect_type': 'damage_per_discard_psychic',
                                                          'params': {'base': 80,
                                                                     'per_card': 10}}]}}}},
 'sv1-107': {'name': '天然雀',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 50,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '三连突刺',
                          'cost': ['Psychic'],
                          'damage': '10×',
                          'text': '抛掷3次硬币，造成正面次数×10伤害。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'三连突刺': {'effects': [{'effect_type': 'coin_flip_triple',
                                                            'params': {'flips': 3,
                                                                       'damage_per_head': 10}}]}}}},
 'sv1-108': {'name': '天然鸟',
             'supertype': 'Pokémon',
             'subtypes': ['Stage 1'],
             'hp': 100,
             'types': ['Psychic'],
             'evolvesFrom': '天然雀',
             'abilities': [{'name': '以太感知',
                            'text': '在自己的回合可以使用1次。选择自己手牌中的1张「基本超能量」，附着于备战宝可梦身上。然后，从自己牌库上方抽取2张卡牌。',
                            'type': 'Ability'}],
             'attacks': [{'name': '超念力',
                          'cost': ['Psychic', 'Colorless', 'Colorless'],
                          'damage': '80',
                          'text': ''}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'abilities': {'以太感知': {'trigger': '',
                                                 'effects': [{'effect_type': 'energy_attach',
                                                              'params': {'amount': 1,
                                                                         'from_zone': 'hand',
                                                                         'filter': 'basic_psychic',
                                                                         'to': 'bench'}},
                                                             {'effect_type': 'draw',
                                                              'params': {'amount': 2,
                                                                         'player': 'self'}}]}},
                          'attacks': {'超念力': {'effects': []}}}},
 'sv1-109': {'name': '月石',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 90,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '循环抽取',
                          'cost': ['Psychic'],
                          'damage': '0',
                          'text': '将自己的1张手牌放于弃牌区。若这样做，则从自己牌库上方抽取3张卡牌。'},
                         {'name': '月亮强念',
                          'cost': ['Colorless', 'Colorless', 'Colorless'],
                          'damage': '30+',
                          'text': '追加造成这只宝可梦身上附有的超能量数量×30点伤害。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'循环抽取': {'effects': [{'effect_type': 'discard_then_draw',
                                                            'params': {'discard_amount': 1,
                                                                       'draw_amount': 3}}]},
                                      '月亮强念': {'effects': [{'effect_type': 'damage_per_self_energy',
                                                            'params': {'base': 30,
                                                                       'per_energy': 30,
                                                                       'energy_filter': 'psychic'}}]}}}},
 'sv1-110': {'name': '拉帝亚斯',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 110,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'abilities': [{'name': '薄雾飘浮',
                            'text': '如果这只宝可梦身上附着了超能量的话，则这只宝可梦撤退所需能量全部消除。',
                            'type': 'Ability'}],
             'attacks': [{'name': '念动弹',
                          'cost': ['Psychic', 'Psychic', 'Colorless'],
                          'damage': '100',
                          'text': ''}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless', 'Colorless'],
             'convertedRetreatCost': 2,
             '_effects': {'abilities': {'薄雾飘浮': {'trigger': 'passive',
                                                 'text': '如果这只宝可梦身上附着了超能量的话，则这只宝可梦撤退所需能量全部消除。',
                                                 'effects': [{'effect_type': 'conditional_zero_retreat',
                                                              'params': {'energy_type': 'psychic'}}]}},
                          'attacks': {'念动弹': {'effects': []}}}},
 'sv1-111': {'name': '拉帝欧斯',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 110,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '滑翔', 'cost': ['Colorless'], 'damage': '20', 'text': ''},
                         {'name': '洁净光芒',
                          'cost': ['Psychic', 'Psychic', 'Colorless'],
                          'damage': '180',
                          'text': '选择这只宝可梦身上附着的3个能量，放于弃牌区。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'滑翔': {'effects': []},
                                      '洁净光芒': {'effects': [{'effect_type': 'energy_discard',
                                                            'params': {'amount': 3,
                                                                       'from': 'self',
                                                                       'filter': 'any'}}]}}}},
 'sv1-112': {'name': '代欧奇希斯',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 120,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '精神拳', 'cost': ['Psychic'], 'damage': '30', 'text': ''},
                         {'name': '基因螺旋',
                          'cost': ['Psychic', 'Psychic', 'Psychic'],
                          'damage': '120',
                          'text': '将这只宝可梦身上附着的所有能量，以任意方式转附于备战宝可梦身上。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'精神拳': {'effects': []},
                                      '基因螺旋': {'effects': [{'effect_type': 'energy_relocate',
                                                            'params': {'amount': 99,
                                                                       'from_self': True}}]}}}},
 'sv1-113': {'name': '克雷色利亚',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 120,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '新月生长',
                          'cost': ['Psychic'],
                          'damage': '0',
                          'text': '选择自己牌库中的1张超能量，附着于自己的宝可梦身上。并重洗牌库。如果是后攻玩家的最初回合的话，则可附着的张数变为最多3张，附着于自己的1只宝可梦身上。'},
                         {'name': '光子镭射',
                          'cost': ['Psychic', 'Psychic'],
                          'damage': '30+',
                          'text': '如果自己场上有5个以上（包含5个）能量的话，则追加造成90点伤害。'}],
             'weaknesses': [{'type': 'Darkness', 'value': '×2'}],
             'resistances': [{'type': 'Fighting', 'value': '-30'}],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'新月生长': {'effects': [{'effect_type': 'energy_attach',
                                                            'params': {'amount': 1,
                                                                       'from_zone': 'deck',
                                                                       'filter': 'psychic',
                                                                       'to': 'any',
                                                                       'going_second_bonus': 3}}]},
                                      '光子镭射': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                                            'params': {'bonus': 90,
                                                                       'condition': 'field_energy_ge_5'}}]}}}},
 'sv1-114': {'name': '咚咚鼠',
             'supertype': 'Pokémon',
             'subtypes': ['Basic'],
             'hp': 70,
             'types': ['Psychic'],
             'evolvesFrom': '',
             'attacks': [{'name': '小使者',
                          'cost': ['Colorless'],
                          'damage': '0',
                          'text': '从自己的牌库中选择最多2张基本能量卡，展示后加入手牌。然后重洗牌库。'},
                         {'name': '旋转折返',
                          'cost': ['Psychic', 'Colorless'],
                          'damage': '50',
                          'text': '若希望，可将这只宝可梦与备战宝可梦互换。'}],
             'weaknesses': [{'type': 'Metal', 'value': '×2'}],
             'resistances': [],
             'retreatCost': ['Colorless'],
             'convertedRetreatCost': 1,
             '_effects': {'attacks': {'小使者': {'effects': [{'effect_type': 'search',
                                                           'params': {'from_zone': 'deck',
                                                                      'filter': 'basic_energy',
                                                                      'destination': 'hand',
                                                                      'count': 2,
                                                                      'min_select': 0,
                                                                      'reveal': True}}]},
                                      '旋转折返': {'effects': [{'effect_type': 'switch_self',
                                                            'params': {'optional': True}}]}}}}}
