"""Card definitions: trainer."""

CARDS = {'sv1-150': {'name': '宝可梦交替',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['将自己的战斗宝可梦与1只备战宝可梦互换。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'switch_self', 'params': {}}}},
 'sv1-151': {'name': '巢穴球',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的牌库中选择1张基础宝可梦卡，放置于备战区。然后重洗牌库。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'search',
                                             'params': {'from_zone': 'deck',
                                                        'filter': 'basic_pokemon',
                                                        'destination': 'bench',
                                                        'reveal': True,
                                                        'count': 1}}}},
 'sv1-152': {'name': '神奇糖果',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['选择自己场上的1只基础宝可梦。若手牌中有从那宝可梦进化而来的2阶进化卡，则将其置于该基础宝可梦身上完成进化。此卡无法在自己的第一回合使用，也无法对当回合上场的基础宝可梦使用。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'evolve_skip_stage',
                                             'params': {'skip_to': 'stage2'}}}},
 'sv1-153': {'name': '高级球',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的手牌丢弃2张卡。若如此做，从自己的牌库中选择1张宝可梦卡，展示后加入手牌。然后重洗牌库。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'conditional',
                                             'params': {'cost': {'effect_type': 'discard',
                                                                 'params': {'amount': 2,
                                                                            'from': 'hand'}},
                                                        'on_pay': {'effect_type': 'search',
                                                                   'params': {'from_zone': 'deck',
                                                                              'filter': 'pokemon',
                                                                              'destination': 'hand',
                                                                              'reveal': True,
                                                                              'count': 1}}}}}},
 'sv1-170': {'name': '电气发生器',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['查看自己牌库上方的5张卡，从中选择最多2张基本雷能量卡，以任意方式附于备战区的雷宝可梦身上。将其他卡放回牌库并重洗。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'look_top_deck',
                                             'params': {'count': 5,
                                                        'take': 2,
                                                        'shuffle_rest': True,
                                                        'filter': 'lightning_energy',
                                                        'destination': 'bench_energy',
                                                        'target_pokemon_type': 'Lightning',
                                                        'min_select': 0}}}},
 'sv1-171': {'name': '能量回收',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的弃牌区中选择最多2张基本能量卡加入手牌。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'search',
                                             'params': {'from_zone': 'discard',
                                                        'filter': 'basic_energy',
                                                        'destination': 'hand',
                                                        'count': 2,
                                                        'min_select': 0,
                                                        'reveal': True}}}},
 'sv1-176': {'name': '裁判',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['双方玩家将所有手牌放回牌库并洗牌。然后，双方玩家各从牌库上方抽取4张卡。'],
             'trainer_type': 'Supporter',
             '_effects': {'trainer_effect': {'effect_type': 'judge', 'params': {'draw': 4}}}},
 'sv1-180': {'name': '妮莫',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['从自己的牌库上方抽取3张卡。'],
             'trainer_type': 'Supporter',
             '_effects': {'trainer_effect': {'effect_type': 'draw',
                                             'params': {'amount': 3, 'player': 'self'}}}},
 'sv1-189': {'name': '博士的研究',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['将自己的所有手牌丢弃，然后从牌库上方抽取7张卡。'],
             'trainer_type': 'Supporter',
             '_effects': {'trainer_effect': {'effect_type': 'discard_draw',
                                             'params': {'discard_hand': True, 'draw': 7}}}},
 'sv1-201': {'name': '不服输头带',
             'supertype': 'Trainer',
             'subtypes': ['Tool'],
             'rules': ['如果自己的剩余奖赏卡张数，比对手的剩余奖赏卡张数多的话，则身上放有这张卡牌的宝可梦所使用的招式，给对手的战斗宝可梦造成的伤害「+30」。'],
             'trainer_type': 'Tool',
             '_effects': {'trainer_effect': {'effect_type': 'tool',
                                             'params': {'effect': 'damage_boost_when_behind'}}}},
 'sv1-202': {'name': '勇气护符',
             'supertype': 'Trainer',
             'subtypes': ['Tool'],
             'rules': ['身上放有这张卡牌的基础宝可梦的最大HP「+50」。'],
             'trainer_type': 'Tool',
             '_effects': {'trainer_effect': {'effect_type': 'tool',
                                             'params': {'effect': 'hp_boost_basic'}}}},
 'sv1-203': {'name': '克拉拉',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['选择自己弃牌区中最多2张宝可梦，和最多2张基本能量，在给对手看过之后，加入手牌。（可只选择宝可梦或只选择基本能量。）'],
             'trainer_type': 'Supporter',
             '_effects': {'trainer_effect': {'effect_type': 'clara',
                                             'params': {'pokemon_count': 2, 'energy_count': 2}}}},
 'sv1-204': {'name': '派帕',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['选择自己牌库中「物品」和「宝可梦道具」各1张，在给对手看过之后，加入手牌。并重洗牌库。'],
             'trainer_type': 'Supporter',
             '_effects': {'trainer_effect': {'effect_type': 'arven', 'params': {}}}},
 'sv2-cand': {'name': '小菘',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['查看自己牌库上方7张卡牌，选择其中任意数量的水宝可梦和水能量，在给对手看过之后，加入手牌。将剩余的卡牌放回牌库并重洗牌库。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'look_top_deck',
                                              'params': {'count': 7,
                                                         'take': 99,
                                                         'shuffle_rest': True,
                                                         'min_select': 0,
                                                         'filter': 'water_pokemon_and_energy'}}}},
 'sv2-catch': {'name': '宝可梦捕捉器',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['抛掷1次硬币如果为正面，则选择对手的1只备战宝可梦，将其与战斗宝可梦互换。'],
               'trainer_type': 'Item',
               '_effects': {'trainer_effect': {'effect_type': 'coin_flip',
                                               'params': {'on_heads': [{'effect_type': 'switch_opponent',
                                                                        'params': {'you_choose': True}}],
                                                          'on_tails': []}}}},
 'sv2-young': {'name': '短裤小子',
               'supertype': 'Trainer',
               'subtypes': ['Supporter'],
               'rules': ['将自己的手牌全部放回牌库并重洗牌库。然后，从牌库上方抽取5张卡牌。'],
               'trainer_type': 'Supporter',
               '_effects': {'trainer_effect': {'effect_type': 'shuffle_draw',
                                               'params': {'shuffle_hand': True,
                                                          'draw': 5,
                                                          'affect': 'self_only'}}}},
 'sv3-134': {'name': '厉害钓竿',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的弃牌区选择宝可梦卡与基本能量卡合计最多3张，放回牌库并重洗。'],
             'trainer_type': 'Item',
             '_effects': {'trainer_effect': {'effect_type': 'shuffle_from_discard',
                                             'params': {'count': 3,
                                                        'filter': 'pokemon_and_energy'}}}},
 'svf-ensw2': {'name': '能量转移',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['选择自己场上宝可梦身上附着的1个基本能量，转附于自己其他宝可梦身上。'],
               'trainer_type': 'Item',
               '_effects': {'trainer_effect': {'effect_type': 'energy_relocate',
                                               'params': {'amount': 1,
                                                          'energy_type': 'basic_energy'}}}},
 'svf-houb': {'name': '凰檗',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己的1张手牌，放回牌库下方。然后，从牌库上方抽取卡牌，直到自己的手牌变为5张为止。',
                        '（如果自己的手牌仅有这1张卡牌的话，则无法使用这张卡牌。）'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'houb',
                                              'params': {'target_hand_size': 5}}}},
 'svf-potion': {'name': '伤药',
                'supertype': 'Trainer',
                'subtypes': ['Item'],
                'rules': ['选择自己1只宝可梦回复「30」HP。'],
                'trainer_type': 'Item',
                '_effects': {'trainer_effect': {'effect_type': 'potion_heal',
                                                'params': {'amount': 30}}}},
 'svg-beri': {'name': '贝里菈',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['从自己的牌库上方抽取卡牌，直到自己的手牌张数比对手的手牌张数多1张为止。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'draw_until_more', 'params': {}}}},
 'svg-chef': {'name': '西餐厨师',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['回复自己的战斗宝可梦「70」点HP。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'heal',
                                              'params': {'amount': 70, 'target': 'self'}}}},
 'svg2-exps': {'name': '学习装置',
               'supertype': 'Trainer',
               'subtypes': ['Tool'],
               'rules': ['每当自己的战斗宝可梦，受到对手宝可梦的招式的伤害而昏厥时，可选择该战斗宝可梦身上附着的1张基本能量，转附于身上放有这张卡牌的宝可梦身上。'],
               'trainer_type': 'Tool',
               '_effects': {'trainer_effect': {'effect_type': 'tool_exp_share', 'params': {}}}},
 'svg2-gard': {'name': '菜种的活力',
               'supertype': 'Trainer',
               'subtypes': ['Supporter'],
               'rules': ['从自己牌库上方抽取2张卡牌。然后，选择自己手牌中最多2张G能量，附着于1只备战宝可梦身上。'],
               'trainer_type': 'Supporter',
               '_effects': {'trainer_effect': {'effect_type': 'draw_and_attach_energy',
                                               'params': {'energy_count': 2,
                                                          'energy_type': 'Grass',
                                                          'min_select': 0}}}},
 'svg2-hamm': {'name': '粉碎之锤',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['抛掷1次硬币如果为正面，则选择对手场上宝可梦身上附着的1个能量，放于弃牌区。'],
               'trainer_type': 'Item',
               '_effects': {'trainer_effect': {'effect_type': 'coin_flip_energy_discard',
                                               'params': {}}}},
 'svi-cait': {'name': '嘉德丽雅',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己任意数量的手牌，以任意顺序重新排列，放回牌库下方。然后，从牌库上方抽取与放回牌库的卡牌数量相同张数的卡牌。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'hand_to_bottom_draw', 'params': {}}}},
 'svi-enst': {'name': '能量签',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['查看自己牌库上方7张卡牌。选择其中1张能量，在给对手看过之后，加入手牌。将剩余的卡牌放回牌库并重洗牌库。'],
              'trainer_type': 'Item',
              '_effects': {'trainer_effect': {'effect_type': 'look_top_deck',
                                              'params': {'count': 7,
                                                         'take': 1,
                                                         'filter': 'energy',
                                                         'destination': 'hand',
                                                         'shuffle_rest': True}}}},
 'svi-erec': {'name': '能量再利用',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己弃牌区中最多5张基本能量，在给对手看过之后，放回牌库并重洗牌库。'],
              'trainer_type': 'Item',
              '_effects': {'trainer_effect': {'effect_type': 'shuffle_from_discard',
                                              'params': {'count': 5, 'filter': 'basic_energy'}}}},
 'svi-mela': {'name': '梅洛可',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['这张卡牌，只有在上一个对手的回合，自己的宝可梦昏厥时才可使用。',
                        '选择自己弃牌区中的1张「基本火能量」，附着于自己的宝可梦身上。若这样做，则从牌库上方抽取卡牌，直到自己的手牌变为6张为止。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'conditional',
                                              'params': {'condition': 'ko_last_opponent_turn',
                                                         'cost': None,
                                                         'on_pay': [{'effect_type': 'attach_from_discard',
                                                                     'params': {'amount': 1,
                                                                                'energy_type': 'basic_fire',
                                                                                'target': 'self_or_bench'}},
                                                                    {'effect_type': 'draw_until',
                                                                     'params': {'target_hand_size': 6}}]}}}},
 'svi-nemb': {'name': '妮莫的背包',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己弃牌区中最多2张「妮莫」，在给对手看过之后，加入手牌。'],
              'trainer_type': 'Item',
              '_effects': {'trainer_effect': {'effect_type': 'search',
                                              'params': {'from_zone': 'discard',
                                                         'filter': 'any',
                                                         'filter_name': '妮莫',
                                                         'destination': 'hand',
                                                         'reveal': True,
                                                         'count': 2,
                                                         'min_select': 0}}}},
 'svi-popp': {'name': '波琵',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己场上1只宝可梦身上附着的最多2个能量，转附于自己的1只其他宝可梦身上。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'energy_relocate',
                                              'params': {'amount': 2,
                                                         'min_select': 0,
                                                         'same_target': True}}}},
 'svl-ensw': {'name': '能量输送',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己牌库中的1张基本能量，在给对手看过之后，加入手牌。并重洗牌库。'],
              'trainer_type': 'Item',
              '_effects': {'trainer_effect': {'effect_type': 'search',
                                              'params': {'from_zone': 'deck',
                                                         'filter': 'basic_energy',
                                                         'destination': 'hand',
                                                         'count': 1,
                                                         'reveal': True}}}},
 'svl-trks': {'name': '健行鞋',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['查看自己牌库上方1张卡牌，将那张卡牌加入手牌。或者，将那张卡牌放于弃牌区，从自己牌库上方抽取1张卡牌。'],
              'trainer_type': 'Item',
              '_effects': {'trainer_effect': {'effect_type': 'trekking_shoes', 'params': {}}}},
 'svl-vitb': {'name': '活力头带',
              'supertype': 'Trainer',
              'subtypes': ['Tool'],
              'rules': ['身上放有这张卡牌的宝可梦所使用的招式，给对手的战斗宝可梦造成的伤害「+10」。'],
              'trainer_type': 'Tool',
              '_effects': {'trainer_effect': {'effect_type': 'tool',
                                              'params': {'effect': 'damage_boost_10'}}}},
 'svl-zinn': {'name': '希嘉娜的决心',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['这张卡牌，只有将自己的2张手牌放于弃牌区后才可使用。', '从自己的牌库上方抽取与对手场上宝可梦数量相同张数的卡牌。'],
              'trainer_type': 'Supporter',
              '_effects': {'trainer_effect': {'effect_type': 'zinnia_resolve', 'params': {}}}},
 'svm-marnie-pride': {'name': '玛俐的自尊',
                      'supertype': 'Trainer',
                      'subtypes': ['Supporter'],
                      'rules': ['选择自己弃牌区中的1张基本能量，附着于备战宝可梦身上。'],
                      'trainer_type': 'Supporter',
                      '_effects': {'trainer_effect': {'effect_type': 'attach_from_discard',
                                                      'params': {'amount': 1,
                                                                 'energy_type': 'basic_energy',
                                                                 'target': 'bench',
                                                                 'select_source': True}}}}}
