"""Card definitions: water."""

CARDS = {'sv1-49': {'name': '拉普拉斯',
            'supertype': 'Pokémon',
            'subtypes': ['Basic'],
            'hp': 130,
            'types': ['Water'],
            'evolvesFrom': '',
            'attacks': [{'name': '愤怒冷冻',
                         'cost': ['Water', 'Water', 'Colorless'],
                         'damage': '110',
                         'text': '在上一个对手的回合，如果因为招式的伤害，而导致自己的宝可梦昏厥的话，则使对手的战斗宝可梦陷入麻痹状态。'}],
            'weaknesses': [{'type': 'Metal', 'value': '×2'}],
            'resistances': [],
            'retreatCost': ['Colorless', 'Colorless'],
            'convertedRetreatCost': 2,
            '_effects': {'attacks': {'愤怒冷冻': {'effects': [{'effect_type': 'conditional_status',
                                                           'params': {'status': 'paralyzed',
                                                                      'target': 'opponent_active',
                                                                      'condition': 'ko_by_attack_damage_last_turn'}}]}}}},
 'sv2-38': {'name': '呱呱泡蛙',
            'supertype': 'Pokémon',
            'subtypes': ['Basic'],
            'hp': 70,
            'types': ['Water'],
            'evolvesFrom': '',
            'attacks': [{'name': '跳一下',
                         'cost': ['Water'],
                         'damage': '30',
                         'text': '抛掷1次硬币如果为反面，则这个招式失败。'}],
            'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
            'resistances': [],
            'retreatCost': ['Colorless'],
            'convertedRetreatCost': 1,
            '_effects': {'attacks': {'跳一下': {'effects': [{'effect_type': 'coin_flip',
                                                          'params': {'on_heads': [],
                                                                     'on_tails': [{'effect_type': 'attack_fail',
                                                                                   'params': {}}]}}]}}}},
 'sv2-39': {'name': '呱头蛙',
            'supertype': 'Pokémon',
            'subtypes': ['Stage 1'],
            'hp': 90,
            'types': ['Water'],
            'evolvesFrom': '呱呱泡蛙',
            'attacks': [{'name': '折返瞬击',
                         'cost': ['Water', 'Water'],
                         'damage': '40',
                         'text': '若希望，可将这只宝可梦与备战宝可梦互换。'}],
            'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
            'resistances': [],
            'retreatCost': ['Colorless'],
            'convertedRetreatCost': 1,
            '_effects': {'attacks': {'折返瞬击': {'effects': [{'effect_type': 'switch_self',
                                                           'params': {'optional': True}}]}}}},
 'sv2-delib': {'name': '信使鸟',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 60,
               'types': ['Water'],
               'evolvesFrom': '',
               'abilities': [],
               'attacks': [{'name': '双重抽取', 'cost': [], 'damage': '0', 'text': '从自己牌库上方抽取2张卡牌。'},
                           {'name': '冰之翼',
                            'cost': ['Water', 'Colorless'],
                            'damage': '30',
                            'text': ''}],
               'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'双重抽取': {'effects': [{'effect_type': 'draw',
                                                              'params': {'amount': 2,
                                                                         'player': 'self'}}]},
                                        '冰之翼': {'effects': []}}}},
 'sv2-glast': {'name': '雪暴马',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 130,
               'types': ['Water'],
               'evolvesFrom': '',
               'abilities': [],
               'attacks': [{'name': '冻结',
                            'cost': ['Water', 'Colorless'],
                            'damage': '40',
                            'text': '在下一个对手的回合，受到这个招式影响的基础宝可梦，无法使用招式。'},
                           {'name': '疯狂冲撞',
                            'cost': ['Water', 'Water', 'Colorless'],
                            'damage': '130',
                            'text': '给这只宝可梦也造成30点伤害。'}],
               'weaknesses': [{'type': 'Metal', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless'],
               'convertedRetreatCost': 2,
               '_effects': {'attacks': {'冻结': {'effects': [{'effect_type': 'attack_lock_basic',
                                                            'params': {'target': 'opponent_active'}}]},
                                        '疯狂冲撞': {'effects': [{'effect_type': 'damage_counter_self',
                                                              'params': {'amount': 30,
                                                                         'damage_kind': 'self_damage'}}]}}}},
 'sv2-grex': {'name': '甲贺忍蛙ex',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 2', 'ex'],
              'hp': 300,
              'types': ['Water'],
              'evolvesFrom': '呱头蛙',
              'rules': ['宝可梦ex规则：当你的宝可梦ex被击倒时，对手获得2张奖赏卡。'],
              'abilities': [],
              'attacks': [{'name': '隐蔽手里剑',
                           'cost': ['Colorless'],
                           'damage': '0',
                           'text': '对对手的1只宝可梦造成40点伤害。（对备战宝可梦不计算弱点·抗性）'},
                          {'name': '激流斩',
                           'cost': ['Water', 'Water'],
                           'damage': '120+',
                           'text': '如果对手的战斗宝可梦身上有伤害指示物，则追加造成120点伤害。'}],
              'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1,
              '_effects': {'attacks': {'隐蔽手里剑': {'effects': [{'effect_type': 'any_pokemon_damage',
                                                              'params': {'amount': 40,
                                                                         'player': 'opponent',
                                                                         'bench_skips_type_matchups': True}}]},
                                       '激流斩': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                                            'params': {'bonus': 120,
                                                                       'condition': 'opponent_active_damaged'}}]}}}},
 'sv2-keldeo': {'name': '凯路迪欧',
                'supertype': 'Pokémon',
                'subtypes': ['Basic'],
                'hp': 110,
                'types': ['Water'],
                'evolvesFrom': '',
                'abilities': [],
                'attacks': [{'name': '踢飞', 'cost': ['Colorless'], 'damage': '20', 'text': ''},
                            {'name': '队列之力',
                             'cost': ['Water', 'Colorless'],
                             'damage': '10+',
                             'text': '追加造成自己备战宝可梦数量×20点伤害。'}],
                'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
                'resistances': [],
                'retreatCost': ['Colorless'],
                'convertedRetreatCost': 1,
                '_effects': {'attacks': {'踢飞': {'effects': []},
                                         '队列之力': {'effects': [{'effect_type': 'damage_plus_bench',
                                                               'params': {'base': 10,
                                                                          'per_bench': 20,
                                                                          'count_own_bench': True}}]}}}},
 'sv2-starm': {'name': '宝石海星',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 1'],
               'hp': 90,
               'types': ['Water'],
               'evolvesFrom': '海星星',
               'abilities': [{'name': '神秘彗星',
                              'text': '在自己的回合可以使用1次。给对手的1只宝可梦身上，放置2个伤害指示物。然后，将这只宝可梦，以及放于其身上的所有卡牌，放于弃牌区。',
                              'type': 'Ability'}],
               'attacks': [{'name': '高速攻击',
                            'cost': ['Water', 'Colorless'],
                            'damage': '50',
                            'text': ''}],
               'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'abilities': {'神秘彗星': {'trigger': '',
                                                   'effects': [{'effect_type': 'place_counters_and_self_discard',
                                                                'params': {'counters': 2,
                                                                           'target': 'opponent_any'}}]}},
                            'attacks': {'高速攻击': {'effects': []}}}},
 'sv2-staryu': {'name': '海星星',
                'supertype': 'Pokémon',
                'subtypes': ['Basic'],
                'hp': 60,
                'types': ['Water'],
                'evolvesFrom': '',
                'abilities': [],
                'attacks': [{'name': '高速星星',
                             'cost': ['Water', 'Colorless'],
                             'damage': '30',
                             'text': '这个招式的伤害，不计算弱点、抗性以及对手战斗宝可梦身上所附加的效果。'}],
                'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
                'resistances': [],
                'retreatCost': ['Colorless'],
                'convertedRetreatCost': 1,
                '_effects': {'attacks': {'高速星星': {'effects': [{'effect_type': 'attack_flags',
                                                               'params': {'ignore_weakness': True,
                                                                          'ignore_resistance': True,
                                                                          'ignore_defender_damage_effects': True}}]}}}},
 'sv2-tatsu': {'name': '米立龙',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 70,
               'types': ['Water'],
               'evolvesFrom': '',
               'abilities': [],
               'attacks': [{'name': '预先准备',
                            'cost': ['Water'],
                            'damage': '0',
                            'text': '选择自己牌库中最多2张「基本水能量」，附着于自己的1只基础宝可梦身上，并重洗牌库。'},
                           {'name': '上弓折返',
                            'cost': ['Water'],
                            'damage': '30',
                            'text': '将这只宝可梦，以及放于其身上的所有卡牌，放回手牌。'}],
               'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1,
               '_effects': {'attacks': {'预先准备': {'effects': [{'effect_type': 'energy_attach',
                                                              'params': {'amount': 2,
                                                                         'from_zone': 'deck',
                                                                         'filter': 'basic_water',
                                                                         'to': 'self_basic',
                                                                         'min_select': 0}}]},
                                        '上弓折返': {'effects': [{'effect_type': 'return_to_hand',
                                                              'params': {}}]}}}},
 'svg-ceti': {'name': '浩大鲸',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 180,
              'types': ['Water'],
              'evolvesFrom': '走鲸',
              'attacks': [{'name': '头突',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '50',
                           'text': ''},
                          {'name': '扫除冲撞',
                           'cost': ['Water', 'Colorless', 'Colorless'],
                           'damage': '200-',
                           'text': '这个招式的伤害，会被减少相当于这只宝可梦身上放置的伤害指示物数量×20的数值。'}],
              'weaknesses': [{'type': 'Metal', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless', 'Colorless'],
              'convertedRetreatCost': 3,
              '_effects': {'attacks': {'头突': {'effects': []},
                                       '扫除冲撞': {'effects': [{'effect_type': 'damage_self_penalty',
                                                             'params': {'base': 200,
                                                                        'per_counter': 20}}]}}}},
 'svg-ceto': {'name': '走鲸',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 80,
              'types': ['Water'],
              'evolvesFrom': '',
              'attacks': [{'name': '撞击',
                           'cost': ['Colorless', 'Colorless'],
                           'damage': '30',
                           'text': ''}],
              'weaknesses': [{'type': 'Metal', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2,
              '_effects': {'attacks': {'撞击': {'effects': []}}}},
 'svg2-empo': {'name': '帝王拿波',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 2'],
               'hp': 160,
               'types': ['Water'],
               'evolvesFrom': '波皇子',
               'abilities': [{'name': '紧急上浮',
                              'text': '在自己的回合，如果这张卡牌在弃牌区，且自己没有手牌的话，则可使用1次。将这张卡牌放于备战区。然后，从自己的牌库上方抽取3张卡牌。',
                              'type': 'Ability'}],
               'attacks': [{'name': '水之矢',
                            'cost': ['Water'],
                            'damage': '0',
                            'text': '给对手的1只宝可梦，造成60点伤害。[备战宝可梦不计算弱点、抗性。]'}],
               'weaknesses': [{'type': 'Lightning', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless'],
               'convertedRetreatCost': 2,
               '_effects': {'abilities': {'紧急上浮': {'trigger': 'on_turn',
                                                   'effects': [{'effect_type': 'ability_discard_revive',
                                                                'params': {'card_id': 'svg2-empo'}}]}},
                            'attacks': {'水之矢': {'effects': [{'effect_type': 'any_pokemon_damage',
                                                             'params': {'amount': 60,
                                                                        'bench_skips_type_matchups': True}}]}}}}}
