#!/usr/bin/env python

import sys
import os
from SCons.Script import Default, Environment
rules_source_root = os.path.abspath(os.path.join("..", "ptcg_core", "src"))
common_root = os.path.abspath(os.path.join("..", "common"))
repo_root = os.path.abspath(os.path.join("..", ".."))
json_root = os.path.join(repo_root, ".tools", "native", "nlohmann-json", "include")

env = Environment(ENV=os.environ)
env.Append(CPPPATH=["src", rules_source_root, common_root, json_root])
if sys.platform == "win32":
    env.Append(CXXFLAGS=["/EHsc", "/std:c++17", "/O2", "/utf-8"])
else:
    env.Append(CXXFLAGS=["-std=c++17", "-O2"])

test_objects = [
    env.Object(os.path.join("build", "challenge_support"), "src/challenge_support.cpp")[0],
    env.Object(
        os.path.join("build", "challenge_tactics_test"),
        "tests/challenge_tactics_test.cpp",
    )[0],
    env.Object(
        os.path.join("build", "ptcg_traditional_strategy"),
        "src/ptcg_traditional_strategy.cpp",
    )[0],
    env.Object(
        os.path.join("build", "ptcg_traditional_infoset"),
        "src/ptcg_traditional_infoset.cpp",
    )[0],
    env.Object(
        os.path.join("build", "ptcg_random"),
        os.path.join(rules_source_root, "ptcg_random.cpp"),
    )[0],
]
program = env.Program(
    os.path.join("bin", "challenge_core_tests"),
    source=test_objects,
)
env.NoCache(program)
Default(program)
