"""Built-in card templates: fire."""

TEMPLATES = {'svi-chim': {'name': '小火焰猴',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 50,
              'types': ['Fire'],
              'evolvesFrom': '',
              'attacks': [{'name': '火花',
                           'cost': ['Fire'],
                           'damage': '30',
                           'text': '选择附着于这只宝可梦身上的1个能量，放于弃牌区。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svi-monf': {'name': '猛火猴',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 80,
              'types': ['Fire'],
              'evolvesFrom': '小火焰猴',
              'attacks': [{'name': '火焰', 'cost': ['Fire'], 'damage': '30', 'text': ''},
                          {'name': '喷射火焰',
                           'cost': ['Fire', 'Colorless'],
                           'damage': '50',
                           'text': '选择附着于这只宝可梦身上的1个能量，放于弃牌区。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svi-infr': {'name': '烈焰猴',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 2'],
              'hp': 150,
              'types': ['Fire'],
              'evolvesFrom': '猛火猴',
              'attacks': [{'name': '螺旋业火',
                           'cost': ['Fire'],
                           'damage': '0',
                           'text': '将自己牌库上方5张翻到正面。造成其中能量张数×80伤害。正面朝上的能量放于弃牌区，剩余卡牌放回牌库并重洗。'},
                          {'name': '燃烧踢',
                           'cost': ['Fire', 'Colorless'],
                           'damage': '160',
                           'text': '将附着于这只宝可梦身上的能量全部放于弃牌区。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svi-ente': {'name': '炎帝',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 130,
              'types': ['Fire'],
              'evolvesFrom': '',
              'abilities': [{'name': '压迫感', 'text': '只要这只宝可梦在战斗场上，对手战斗宝可梦使用的招式伤害「-20」。', 'type': 'Ability'}],
              'attacks': [{'name': '火焰之球',
                           'cost': ['Colorless', 'Colorless', 'Colorless'],
                           'damage': '60',
                           'text': '追加这只宝可梦身上附着的火能量数量×20伤害。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2},
 'svi-hrot': {'name': '加热洛托姆',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 90,
              'types': ['Fire'],
              'evolvesFrom': '',
              'attacks': [{'name': '高温冲撞',
                           'cost': ['Fire', 'Fire'],
                           'damage': '100',
                           'text': '给这只宝可梦也造成40伤害。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svi-chiy': {'name': '古玉鱼',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 110,
              'types': ['Fire'],
              'evolvesFrom': '',
              'attacks': [{'name': '闪焰生成',
                           'cost': ['Fire'],
                           'damage': '0',
                           'text': '选择自己弃牌区中最多2张基本火能量，附着于自己的1只宝可梦身上。'},
                          {'name': '嫉妒业火',
                           'cost': ['Fire', 'Fire'],
                           'damage': '50',
                           'text': '在上一个对手的回合，如果因为招式的伤害而导致自己的宝可梦昏厥的话，则追加造成90伤害。'}],
              'weaknesses': [{'type': 'Water', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1}}
