"""Built-in card templates: lightning."""

TEMPLATES = {'svl-pikaex': {'name': '皮卡丘ex',
                'supertype': 'Pokémon',
                'subtypes': ['Basic', 'ex'],
                'hp': 190,
                'types': ['Lightning'],
                'evolvesFrom': '',
                'rules': ['宝可梦ex规则：当你的宝可梦ex被击倒时，对手获得2张奖品卡。'],
                'attacks': [{'name': '皮卡拳', 'cost': ['Colorless'], 'damage': '30', 'text': ''},
                            {'name': '强劲伏特',
                             'cost': ['Lightning', 'Lightning', 'Colorless'],
                             'damage': '220',
                             'text': '抛掷1次硬币。如果是反面，则将这只宝可梦身上附着的能量全部放于弃牌区。'}],
                'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
                'resistances': [],
                'retreatCost': [],
                'convertedRetreatCost': 0},
 'svl-chin': {'name': '灯笼鱼',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Lightning'],
              'evolvesFrom': '',
              'attacks': [{'name': '电球', 'cost': ['Lightning'], 'damage': '10', 'text': ''}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svl-lant': {'name': '电灯怪',
              'supertype': 'Pokémon',
              'subtypes': ['Stage 1'],
              'hp': 120,
              'types': ['Lightning'],
              'evolvesFrom': '灯笼鱼',
              'attacks': [{'name': '炫目光束',
                           'cost': ['Lightning', 'Colorless'],
                           'damage': '40',
                           'text': '在下一个对手的回合，受到这个招式影响的宝可梦在使用招式时，对手将抛掷1次硬币。如果为反面则那个招式失败。'},
                          {'name': '电球',
                           'cost': ['Lightning', 'Lightning', 'Colorless'],
                           'damage': '120',
                           'text': ''}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless', 'Colorless'],
              'convertedRetreatCost': 2},
 'svl-mare2': {'name': '咩利羊',
               'supertype': 'Pokémon',
               'subtypes': ['Basic'],
               'hp': 60,
               'types': ['Lightning'],
               'evolvesFrom': '',
               'attacks': [{'name': '后踢', 'cost': ['Colorless'], 'damage': '10', 'text': ''},
                           {'name': '电球', 'cost': ['Lightning', 'Colorless'], 'damage': '30', 'text': ''}],
               'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless'],
               'convertedRetreatCost': 1},
 'svl-flaa2': {'name': '茸茸羊',
               'supertype': 'Pokémon',
               'subtypes': ['Stage 1'],
               'hp': 90,
               'types': ['Lightning'],
               'evolvesFrom': '咩利羊',
               'abilities': [{'name': '电气发电机',
                              'text': '在自己的回合可使用1次。选择自己弃牌区中的1张雷能量卡，附着于备战宝可梦身上。',
                              'type': 'Ability'}],
               'attacks': [{'name': '电球',
                            'cost': ['Lightning', 'Lightning', 'Colorless'],
                            'damage': '50',
                            'text': ''}],
               'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
               'resistances': [],
               'retreatCost': ['Colorless', 'Colorless'],
               'convertedRetreatCost': 2},
 'svl-emol': {'name': '电飞鼠',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 70,
              'types': ['Lightning'],
              'evolvesFrom': '',
              'attacks': [{'name': '电击',
                           'cost': ['Lightning'],
                           'damage': '30',
                           'text': '抛掷1次硬币如果为正面，则使对手的战斗宝可梦陷入麻痹状态。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': [],
              'convertedRetreatCost': 0},
 'svl-thun': {'name': '雷电云',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 120,
              'types': ['Lightning'],
              'evolvesFrom': '',
              'attacks': [{'name': '辅助电光',
                           'cost': ['Lightning'],
                           'damage': '30',
                           'text': '若希望，可选择自己手牌中的1张雷能量卡，附着于备战宝可梦身上。'},
                          {'name': '打雷',
                           'cost': ['Lightning', 'Lightning', 'Colorless'],
                           'damage': '130',
                           'text': '给这只宝可梦也造成30点伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1},
 'svl-zera': {'name': '捷拉奥拉',
              'supertype': 'Pokémon',
              'subtypes': ['Basic'],
              'hp': 120,
              'types': ['Lightning'],
              'evolvesFrom': '',
              'attacks': [{'name': '疯狂伏特',
                           'cost': ['Lightning', 'Colorless'],
                           'damage': '70',
                           'text': '给这只宝可梦也造成20点伤害。'}],
              'weaknesses': [{'type': 'Fighting', 'value': '×2'}],
              'resistances': [],
              'retreatCost': ['Colorless'],
              'convertedRetreatCost': 1}}
