"""Release-card text to runtime binding consistency matrix.

The exporter consumes this module instead of maintaining a second hand-written
inventory.  Every non-empty printed rules segment must have at least one
explicit binding, every emitted VM command must exist in the Python registry,
and callers may require exact parity with the peer (Godot) VM registry.
"""
from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path
import json
from typing import Any

from data.card_registry import CardRegistry
from data.deck_definitions import ALL_CARD_IDS
from engine.commands.descriptors import VM_COMMAND_DESCRIPTORS
from engine.commands.vm_contract import VM_IR_VERSION, validate_command_spec


MATRIX_FORMAT_VERSION = 1

SUPPORTED_ENERGY_HOOKS = frozenset({
    "ON_ATTACH",
    "ON_PRIZE_REVEALED",
    "AFTER_DAMAGE",
    "MODIFY_DAMAGE",
})
SUPPORTED_ENERGY_ACTIONS = frozenset({
    "provide_energy",
    "switch_with_active",
    "attach_to_benched_pokemon",
    "draw_cards",
    "modify_damage",
})

# Public choice domains generated by each command family.  This inventory is
# intentionally conservative: a command may resolve without a choice when its
# legal set has one element, while still having the listed constraint when a
# decision exists.
CHOICE_DOMAIN_BY_OP = {
    "attach_energy": "energy_entity_and_target",
    "attach_energy_from_discard": "energy_entity_and_target",
    "choose_damage_target": "pokemon_target",
    "choose_heal_damage": "pokemon_target",
    "conditional_search": "card_entity",
    "discard_cards": "card_entity",
    "discard_energy": "attachment_entity",
    "discard_energy_then_damage": "attachment_entity",
    "discard_hand_then_damage": "card_entity",
    "discard_then_draw_cards": "card_entity",
    "discard_then_revive": "discard_entity",
    "draw_and_attach_energy": "energy_entity_and_target",
    "evolve_skip_stage": "card_and_pokemon_target",
    "flip_coin": "coin_result",
    "flip_coin_repeat_damage": "coin_result",
    "flip_coin_then_discard_energy": "coin_and_attachment_entity",
    "flip_coin_then_ko": "coin_result",
    "flip_until_tails": "coin_result",
    "hand_to_bottom_then_draw": "ordered_card_entities",
    "look_top_attach_energy": "confirm_and_target",
    "look_top_deck": "confirm",
    "recover_clara": "discard_entities",
    "relocate_energy": "attachment_entity_and_target",
    "search_any_and_switch": "card_entity",
    "search_cards": "card_entity",
    "search_item_and_tool": "card_entities",
    "shuffle_from_discard_to_deck": "discard_entities",
    "switch_pokemon": "pokemon_target",
    "trekking_shoes": "confirm",
}


def _command_specs(payload: Any) -> Iterable[Mapping[str, Any]]:
    """Yield command specs, excluding formula-AST ``op`` dictionaries."""
    if isinstance(payload, (list, tuple)):
        for item in payload:
            yield from _command_specs(item)
        return
    if not isinstance(payload, Mapping) or "op" not in payload:
        return
    yield payload
    branches = payload.get("branches", {})
    if isinstance(branches, Mapping):
        for branch in branches.values():
            yield from _command_specs(branch)


def _effect_types(effects: Iterable[Any]) -> list[str]:
    return sorted({
        str(getattr(effect, "effect_type", "") or "")
        for effect in effects or []
        if str(getattr(effect, "effect_type", "") or "")
    })


def _vm_binding(compiled: list[dict], effects: Iterable[Any]) -> dict[str, Any]:
    specs = list(_command_specs(compiled))
    ops = sorted({str(spec.get("op", "") or "") for spec in specs})
    return {
        "kind": "vm",
        "effect_types": _effect_types(effects),
        "ops": ops,
        "choice_domains": sorted({
            CHOICE_DOMAIN_BY_OP[op]
            for op in ops
            if op in CHOICE_DOMAIN_BY_OP
        }),
    }


def _segment(
    *,
    zone: str,
    name: str,
    text: str,
    public_action: str,
    trigger_zone: str,
    hooks: list[str],
    bindings: list[dict[str, Any]],
) -> dict[str, Any]:
    choice_constraints = sorted({
        str(domain)
        for binding in bindings
        for domain in binding.get("choice_domains", [])
        if str(domain)
    })
    return {
        "zone": zone,
        "name": name,
        "text": text,
        "public_action": public_action,
        "trigger_zone": trigger_zone,
        "hooks": sorted(set(hooks)),
        "choice_constraints": choice_constraints,
        "bindings": bindings,
    }


def build_card_rules_matrix(
    *,
    card_ids: Iterable[str] = ALL_CARD_IDS,
    peer_supported_ops: Iterable[str] | None = None,
) -> dict[str, Any]:
    """Build the deterministic 137-card printed-text binding inventory."""
    ids = [str(card_id) for card_id in card_ids]
    if not CardRegistry.is_initialized():
        CardRegistry.initialize(ids)
    python_ops = set(VM_COMMAND_DESCRIPTORS)
    peer_ops = set(str(op) for op in peer_supported_ops) if peer_supported_ops is not None else None
    errors: list[str] = []

    if len(ids) != len(set(ids)):
        errors.append("duplicate card IDs in release card list")
    missing_ids = sorted(set(ids) - set(CardRegistry.all_ids()))
    if missing_ids:
        errors.append(f"unknown or unloaded card IDs: {missing_ids}")
    if peer_ops is not None:
        python_only = sorted(python_ops - peer_ops)
        peer_only = sorted(peer_ops - python_ops)
        if python_only:
            errors.append(f"Python-only VM ops: {python_only}")
        if peer_only:
            errors.append(f"peer-only VM ops: {peer_only}")

    cards: dict[str, Any] = {}
    for card_id in sorted(ids):
        card = CardRegistry.get(card_id)
        if card is None:
            continue
        segments: list[dict[str, Any]] = []

        for attack in card.attacks or []:
            text = str(getattr(attack, "text", "") or "").strip()
            if text:
                segments.append(_segment(
                    zone="attack",
                    name=attack.name,
                    text=text,
                    public_action="DECLARE_ATTACK",
                    trigger_zone="attack",
                    hooks=[],
                    bindings=[_vm_binding(attack.compiled_effects, attack.effects)],
                ))
        for ability in card.abilities or []:
            text = str(getattr(ability, "text", "") or "").strip()
            if text:
                segments.append(_segment(
                    zone="ability",
                    name=ability.name,
                    text=text,
                    public_action=(
                        "USE_ABILITY"
                        if str(getattr(ability, "trigger", "") or "")
                        in {"", "on_turn", "repeatable"}
                        else "AUTOMATIC"
                    ),
                    trigger_zone=str(getattr(ability, "trigger", "") or "manual"),
                    hooks=(
                        [str(getattr(ability, "trigger", "") or "")]
                        if str(getattr(ability, "trigger", "") or "")
                        else []
                    ),
                    bindings=[_vm_binding(ability.compiled_effects, ability.effects)],
                ))

        if card.supertype == "Trainer":
            binding = _vm_binding(card.compiled_trainer_effects, card.trainer_effects)
            for index, raw_text in enumerate(card.rules or []):
                text = str(raw_text or "").strip()
                if text:
                    segments.append(_segment(
                        zone="trainer",
                        name=f"{card.name}#{index + 1}",
                        text=text,
                        public_action="PLAY_TRAINER",
                        trigger_zone="hand",
                        hooks=[],
                        bindings=[binding],
                    ))
        elif card.supertype == "Energy":
            energy_bindings = []
            for effect in card.energy_effects or []:
                kind = str(effect.get("kind", "") or "")
                hook = str(effect.get("hook", "") or "")
                action = kind
                effect_payload = effect.get("effect", {})
                if isinstance(effect_payload, Mapping):
                    action = str(effect_payload.get("op", kind) or kind)
                if kind == "modifier" and action == "modifier":
                    action = "modify_damage"
                energy_bindings.append({
                    "kind": "energy_hook",
                    "hook": hook,
                    "action": action,
                    "condition": dict(effect.get("condition", {}) or {}),
                })
                if hook and hook not in SUPPORTED_ENERGY_HOOKS:
                    errors.append(f"{card_id}: unsupported energy hook {hook!r}")
                if action not in SUPPORTED_ENERGY_ACTIONS:
                    errors.append(f"{card_id}: unsupported energy action {action!r}")
            for index, raw_text in enumerate(card.rules or []):
                text = str(raw_text or "").strip()
                if text:
                    segments.append(_segment(
                        zone="energy",
                        name=f"{card.name}#{index + 1}",
                        text=text,
                        public_action="ATTACH_ENERGY" if index == 0 else "AUTOMATIC",
                        trigger_zone="attached_or_prize",
                        hooks=sorted({
                            str(binding.get("hook", "") or "")
                            for binding in energy_bindings
                            if str(binding.get("hook", "") or "")
                        }),
                        bindings=list(energy_bindings),
                    ))
        else:
            # Pokémon rule boxes (for example Pokémon ex prize value) are
            # implemented by core card-state semantics, not attack VM ops.
            for index, raw_text in enumerate(card.rules or []):
                text = str(raw_text or "").strip()
                if text:
                    segments.append(_segment(
                        zone="rule_box",
                        name=f"{card.name}#{index + 1}",
                        text=text,
                        public_action="AUTOMATIC",
                        trigger_zone="core_rules",
                        hooks=[],
                        bindings=[{"kind": "core_rule", "action": "prize_value"}],
                    ))

        used_ops: set[str] = set()
        for segment_index, segment in enumerate(segments):
            bindings = segment["bindings"]
            if not bindings:
                errors.append(f"{card_id}.segments[{segment_index}] has no registered binding")
                continue
            for binding in bindings:
                if binding.get("kind") != "vm":
                    continue
                ops = list(binding.get("ops", []))
                effect_types = list(binding.get("effect_types", []))
                if not ops or not effect_types:
                    errors.append(
                        f"{card_id}.segments[{segment_index}] printed text has no VM effect/action"
                    )
            compiled_groups = []
            zone = segment["zone"]
            if zone == "attack":
                compiled_groups = [
                    attack.compiled_effects
                    for attack in card.attacks
                    if attack.name == segment["name"]
                ]
            elif zone == "ability":
                compiled_groups = [
                    ability.compiled_effects
                    for ability in card.abilities
                    if ability.name == segment["name"]
                ]
            elif zone == "trainer":
                compiled_groups = [card.compiled_trainer_effects]
            for compiled in compiled_groups:
                for spec_index, spec in enumerate(_command_specs(compiled)):
                    used_ops.add(str(spec.get("op", "") or ""))
                    for error in validate_command_spec(
                        spec,
                        supported_ops=python_ops,
                        path=f"{card_id}.{zone}[{spec_index}]",
                    ):
                        errors.append(error)
                    if peer_ops is not None and str(spec.get("op", "")) not in peer_ops:
                        errors.append(
                            f"{card_id}.{zone}[{spec_index}] is not implemented by peer: "
                            f"{spec.get('op', '')}"
                        )

        cards[card_id] = {
            "name": card.name,
            "supertype": card.supertype,
            "segment_count": len(segments),
            "segments": segments,
            "used_vm_ops": sorted(used_ops),
        }

    return {
        "format_version": MATRIX_FORMAT_VERSION,
        "vm_ir_version": VM_IR_VERSION,
        "card_count": len(cards),
        "expected_card_count": len(ids),
        "python_supported_ops": sorted(python_ops),
        "peer_supported_ops": sorted(peer_ops) if peer_ops is not None else None,
        "cards": cards,
        "errors": sorted(set(errors)),
    }


def assert_card_rules_consistent(
    *,
    card_ids: Iterable[str] = ALL_CARD_IDS,
    peer_supported_ops: Iterable[str] | None = None,
) -> dict[str, Any]:
    matrix = build_card_rules_matrix(
        card_ids=card_ids,
        peer_supported_ops=peer_supported_ops,
    )
    if matrix["errors"]:
        raise ValueError("card rules consistency failed: " + "; ".join(matrix["errors"]))
    return matrix


def load_godot_vm_ops(descriptor_path: str | Path) -> frozenset[str]:
    """Read the generated descriptor inventory consumed by Godot."""
    path = Path(descriptor_path)
    payload = json.loads(path.read_text(encoding="utf-8"))
    descriptors = payload.get("descriptors")
    if not isinstance(descriptors, dict):
        raise ValueError(f"Godot VM descriptor payload is invalid in {path}")
    ops = frozenset(str(op) for op in descriptors)
    if not ops:
        raise ValueError(f"Godot VM op inventory is empty in {path}")
    return ops


__all__ = [
    "MATRIX_FORMAT_VERSION",
    "assert_card_rules_consistent",
    "build_card_rules_matrix",
    "load_godot_vm_ops",
]
