"""Aggregated built-in card templates."""

from .colorless import TEMPLATES as COLORLESS_TEMPLATES
from .darkness import TEMPLATES as DARKNESS_TEMPLATES
from .dragon import TEMPLATES as DRAGON_TEMPLATES
from .energy import TEMPLATES as ENERGY_TEMPLATES
from .fighting import TEMPLATES as FIGHTING_TEMPLATES
from .fire import TEMPLATES as FIRE_TEMPLATES
from .grass import TEMPLATES as GRASS_TEMPLATES
from .lightning import TEMPLATES as LIGHTNING_TEMPLATES
from .metal import TEMPLATES as METAL_TEMPLATES
from .psychic import TEMPLATES as PSYCHIC_TEMPLATES
from .trainer import TEMPLATES as TRAINER_TEMPLATES
from .water import TEMPLATES as WATER_TEMPLATES

OFFLINE_CARD_TEMPLATES: dict[str, dict] = {}
OFFLINE_CARD_TEMPLATES.update(COLORLESS_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(DARKNESS_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(DRAGON_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(ENERGY_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(FIGHTING_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(FIRE_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(GRASS_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(LIGHTNING_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(METAL_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(PSYCHIC_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(TRAINER_TEMPLATES)
OFFLINE_CARD_TEMPLATES.update(WATER_TEMPLATES)
