"""Built-in card templates: darkness."""

TEMPLATES = {
    "svd-mabosstiff-ex": {
        "name": "獒教父ex",
        "supertype": "Pokémon",
        "subtypes": ["Stage 1", "ex"],
        "hp": 260,
        "types": ["Darkness"],
        "evolvesFrom": "偶叫獒",
        "attacks": [
            {
                "name": "恫吓",
                "cost": ["Colorless", "Colorless"],
                "damage": "30",
                "text": "在下一个对手的回合，受到这个招式影响的宝可梦所使用招式的伤害「-50」。",
            },
            {
                "name": "自尊獠牙",
                "cost": ["Darkness", "Colorless", "Colorless"],
                "damage": "100+",
                "text": "如果自己的备战宝可梦身上放置有伤害指示物的话，则追加造成120伤害。",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless", "Colorless", "Colorless"],
        "convertedRetreatCost": 3,
    },
    "svd-maschiff": {
        "name": "偶叫獒",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 70,
        "types": ["Darkness"],
        "evolvesTo": ["獒教父ex"],
        "attacks": [
            {
                "name": "踢飞",
                "cost": ["Colorless", "Colorless"],
                "damage": "20",
                "text": "",
            },
            {
                "name": "锐利之牙",
                "cost": ["Darkness", "Colorless", "Colorless"],
                "damage": "50",
                "text": "",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless", "Colorless"],
        "convertedRetreatCost": 2,
    },
    "svd-dodrio": {
        "name": "嘟嘟利",
        "supertype": "Pokémon",
        "subtypes": ["Stage 1"],
        "hp": 100,
        "types": ["Colorless"],
        "evolvesFrom": "嘟嘟",
        "abilities": [
            {
                "name": "暴走抽取",
                "text": "在自己的回合可以使用1次。给这只宝可梦身上放置1个伤害指示物。然后，从自己牌库上方抽取1张卡牌。",
                "type": "Ability",
            }
        ],
        "attacks": [
            {
                "name": "愤怒之喙",
                "cost": ["Colorless"],
                "damage": "10+",
                "text": "追加造成这只宝可梦身上放置的伤害指示物数量×30伤害。",
            }
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless"],
        "convertedRetreatCost": 1,
    },
    "svd-doduo": {
        "name": "嘟嘟",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 70,
        "types": ["Colorless"],
        "evolvesTo": ["嘟嘟利"],
        "attacks": [
            {
                "name": "突击",
                "cost": ["Colorless"],
                "damage": "30",
                "text": "给这只宝可梦也造成10伤害。",
            }
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless"],
        "convertedRetreatCost": 1,
    },
    "svd-seviper": {
        "name": "饭匙蛇",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 110,
        "types": ["Darkness"],
        "attacks": [
            {
                "name": "锐利之牙",
                "cost": ["Colorless"],
                "damage": "20",
                "text": "",
            },
            {
                "name": "挥落",
                "cost": ["Darkness", "Colorless"],
                "damage": "50+",
                "text": "如果对手的战斗宝可梦为进化宝可梦的话，则追加造成50伤害。",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless"],
        "convertedRetreatCost": 1,
    },
    "svd-absol": {
        "name": "阿勃梭鲁",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 100,
        "types": ["Darkness"],
        "attacks": [
            {
                "name": "漩涡灾祸",
                "cost": ["Darkness"],
                "damage": "10",
                "text": "给对手的所有宝可梦，各造成10点伤害。[备战宝可梦不计算弱点、抗性。]",
            },
            {
                "name": "深挖伤口",
                "cost": ["Darkness", "Colorless"],
                "damage": "50+",
                "text": "如果对手的战斗宝可梦身上放置有伤害指示物的话，则追加造成70点伤害。",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless"],
        "convertedRetreatCost": 1,
    },
    "svd-darkrai": {
        "name": "达克莱伊",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 120,
        "types": ["Darkness"],
        "attacks": [
            {
                "name": "恶梦",
                "cost": ["Darkness", "Colorless"],
                "damage": "30",
                "text": "使对手的战斗宝可梦陷入睡眠状态。",
            },
            {
                "name": "漆黑之刃",
                "cost": ["Darkness", "Darkness", "Colorless"],
                "damage": "130",
                "text": "在下一个自己的回合，这只宝可梦无法使用招式。",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless", "Colorless"],
        "convertedRetreatCost": 2,
    },
    "svd-morpeko": {
        "name": "莫鲁贝可",
        "supertype": "Pokémon",
        "subtypes": ["Basic"],
        "hp": 80,
        "types": ["Darkness"],
        "attacks": [
            {
                "name": "捡食",
                "cost": ["Colorless"],
                "damage": "0",
                "text": "选择自己弃牌区中的1张物品，在给对手看过之后，加入手牌。",
            },
            {
                "name": "空腹撞击",
                "cost": ["Darkness"],
                "damage": "20+",
                "text": "如果自己没有手牌的话，则追加造成90点伤害。",
            },
        ],
        "weaknesses": [],
        "resistances": [],
        "retreatCost": ["Colorless"],
        "convertedRetreatCost": 1,
    },
    "svd-dark-patch": {
        "name": "暗黑补丁",
        "supertype": "Trainer",
        "subtypes": ["Item"],
        "rules": ["选择自己弃牌区中的1张「基本恶能量」，附着于备战区的恶宝可梦身上。"],
        "trainer_type": "Item",
    },
    "svd-hard-belt": {
        "name": "坚硬束带",
        "supertype": "Trainer",
        "subtypes": ["Tool"],
        "rules": ["身上放有这张卡牌的1阶进化宝可梦，受到对手宝可梦的招式的伤害「-30」。"],
        "trainer_type": "Tool",
    },
}
