"""Built-in card templates: energy."""

TEMPLATES = {'sv1-ener-1': {'name': '草能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-2': {'name': '火能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-3': {'name': '水能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-4': {'name': '雷能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-5': {'name': '超能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-6': {'name': '斗能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-7': {'name': '恶能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'sv1-ener-8': {'name': '钢能量', 'supertype': 'Energy', 'subtypes': ['Basic']},
 'svi-jete': {'name': '喷射能量',
              'supertype': 'Energy',
              'subtypes': ['Special'],
              'rules': ['只要这张卡牌被附着于宝可梦身上，就被视作1个[C]能量。', '当将这张卡牌从手牌附着于备战宝可梦身上时，将该宝可梦与战斗宝可梦互换。']},
 'svi-dtur': {'name': '双重涡轮能量',
              'supertype': 'Energy',
              'subtypes': ['Special'],
              'rules': ['只要这张卡牌被附着于宝可梦身上，就被视作2个[C]能量。', '身上附有这张卡牌的宝可梦所使用的招式，给对手的宝可梦造成的伤害「-20」。']},
 'svi-trea': {'name': '宝藏能量',
              'supertype': 'Energy',
              'subtypes': ['Special'],
              'rules': ['只要这张卡牌被附着于宝可梦身上，就被视作1个[C]能量。',
                        '在自己的回合，当从反面朝上的自己的奖赏卡中拿取了这张卡牌时，在加入手牌前，可将这张卡牌附着于自己的宝可梦身上。']},
 'svi-mirc': {'name': '幸运能量',
              'supertype': 'Energy',
              'subtypes': ['Special'],
              'rules': ['只要这张卡牌被附着于宝可梦身上，就被视作1个[C]能量。', '身上附有这张卡牌的宝可梦，在战斗场上受到对手宝可梦的招式的伤害时，从自己的牌库上方抽取1张卡牌。']},
 'svg2-lume': {'name': '夜光能量',
               'supertype': 'Energy',
               'subtypes': ['Special'],
               'rules': ['只要这张卡牌，被附着于宝可梦身上，就被视作1个所有属性的能量。',
                         '如果身上附着了这张卡牌的宝可梦，身上还附着了除这张卡牌以外的特殊能量的话，则这张卡牌被视作1个普通能量。']}}
