"""Built-in card templates: trainer."""

TEMPLATES = {'svf-potion': {'name': '伤药',
                'supertype': 'Trainer',
                'subtypes': ['Item'],
                'rules': ['选择自己1只宝可梦回复「30」HP。'],
                'trainer_type': 'Item'},
 'svf-ensw2': {'name': '能量转移',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['选择自己场上宝可梦身上附着的1个基本能量，转附于自己其他宝可梦身上。'],
               'trainer_type': 'Item'},
 'svf-houb': {'name': '凰檗',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己的1张手牌，放回牌库下方。然后，从牌库上方抽取卡牌，直到自己的手牌变为5张为止。', '（如果自己的手牌仅有这1张卡牌的话，则无法使用这张卡牌。）'],
              'trainer_type': 'Supporter'},
 'sv1-189': {'name': '博士的研究',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['将自己的所有手牌丢弃，然后从牌库上方抽取7张卡。'],
             'trainer_type': 'Supporter'},
 'sv1-176': {'name': '裁判',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['双方玩家将所有手牌放回牌库并洗牌。然后，双方玩家各从牌库上方抽取4张卡。'],
             'trainer_type': 'Supporter'},
 'sv1-180': {'name': '妮莫',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['从自己的牌库上方抽取3张卡。'],
             'trainer_type': 'Supporter'},
 'sv1-150': {'name': '宝可梦交替',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['将自己的战斗宝可梦与1只备战宝可梦互换。'],
             'trainer_type': 'Item'},
 'sv1-151': {'name': '巢穴球',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的牌库中选择1张基础宝可梦卡，放置于备战区。然后重洗牌库。'],
             'trainer_type': 'Item'},
 'sv1-152': {'name': '神奇糖果',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['选择自己场上的1只基础宝可梦。若手牌中有从那宝可梦进化而来的2阶进化卡，则将其置于该基础宝可梦身上完成进化。此卡无法在自己的第一回合使用，也无法对当回合上场的基础宝可梦使用。'],
             'trainer_type': 'Item'},
 'sv1-153': {'name': '高级球',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的手牌丢弃2张卡。若如此做，从自己的牌库中选择1张宝可梦卡，展示后加入手牌。然后重洗牌库。'],
             'trainer_type': 'Item'},
 'sv3-134': {'name': '厉害钓竿',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的弃牌区选择宝可梦卡与基本能量卡合计最多3张，放回牌库并重洗。'],
             'trainer_type': 'Item'},
 'sv1-170': {'name': '电气发生器',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['查看自己牌库上方的5张卡，从中选择最多2张基本雷能量卡，以任意方式附于备战区的雷宝可梦身上。将其他卡放回牌库并重洗。'],
             'trainer_type': 'Item'},
 'sv1-171': {'name': '能量回收',
             'supertype': 'Trainer',
             'subtypes': ['Item'],
             'rules': ['从自己的弃牌区中选择最多2张基本能量卡加入手牌。'],
             'trainer_type': 'Item'},
 'sv2-young': {'name': '短裤小子',
               'supertype': 'Trainer',
               'subtypes': ['Supporter'],
               'rules': ['将自己的手牌全部放回牌库并重洗牌库。然后，从牌库上方抽取5张卡牌。'],
               'trainer_type': 'Supporter'},
 'sv2-cand': {'name': '小菘',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['查看自己牌库上方7张卡牌，选择其中任意数量的水宝可梦和水能量，在给对手看过之后，加入手牌。将剩余的卡牌放回牌库并重洗牌库。'],
              'trainer_type': 'Supporter'},
 'sv2-catch': {'name': '宝可梦捕捉器',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['抛掷1次硬币如果为正面，则选择对手的1只备战宝可梦，将其与战斗宝可梦互换。'],
               'trainer_type': 'Item'},
 'svi-mela': {'name': '梅洛可',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['这张卡牌，只有在上一个对手的回合，自己的宝可梦昏厥时才可使用。',
                        '选择自己弃牌区中的1张「基本火能量」，附着于自己的宝可梦身上。若这样做，则从牌库上方抽取卡牌，直到自己的手牌变为6张为止。'],
              'trainer_type': 'Supporter'},
 'svi-erec': {'name': '能量再利用',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己弃牌区中最多5张基本能量，在给对手看过之后，放回牌库并重洗牌库。'],
              'trainer_type': 'Item'},
 'svi-enst': {'name': '能量签',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['查看自己牌库上方7张卡牌。选择其中1张能量，在给对手看过之后，加入手牌。将剩余的卡牌放回牌库并重洗牌库。'],
              'trainer_type': 'Item'},
 'svi-nemb': {'name': '妮莫的背包',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己弃牌区中最多2张「妮莫」，在给对手看过之后，加入手牌。'],
              'trainer_type': 'Item'},
 'svi-cait': {'name': '嘉德丽雅',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己任意数量的手牌，以任意顺序重新排列，放回牌库下方。然后，从牌库上方抽取与放回牌库的卡牌数量相同张数的卡牌。'],
              'trainer_type': 'Supporter'},
 'svi-popp': {'name': '波琵',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['选择自己场上1只宝可梦身上附着的最多2个能量，转附于自己的1只其他宝可梦身上。'],
              'trainer_type': 'Supporter'},
 'sv1-201': {'name': '不服输头带',
             'supertype': 'Trainer',
             'subtypes': ['Tool'],
             'rules': ['如果自己的剩余奖赏卡张数，比对手的剩余奖赏卡张数多的话，则身上放有这张卡牌的宝可梦所使用的招式，给对手的战斗宝可梦造成的伤害「+30」。'],
             'trainer_type': 'Tool'},
 'sv1-202': {'name': '勇气护符',
             'supertype': 'Trainer',
             'subtypes': ['Tool'],
             'rules': ['身上放有这张卡牌的基础宝可梦的最大HP「+50」。'],
             'trainer_type': 'Tool'},
 'sv1-203': {'name': '克拉拉',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['选择自己弃牌区中最多2张宝可梦，和最多2张基本能量，在给对手看过之后，加入手牌。（可只选择宝可梦或只选择基本能量。）'],
             'trainer_type': 'Supporter'},
 'sv1-204': {'name': '派帕',
             'supertype': 'Trainer',
             'subtypes': ['Supporter'],
             'rules': ['选择自己牌库中「物品」和「宝可梦道具」各1张，在给对手看过之后，加入手牌。并重洗牌库。'],
             'trainer_type': 'Supporter'},
 'svm-marnie-pride': {'name': '玛俐的自尊',
                      'supertype': 'Trainer',
                      'subtypes': ['Supporter'],
                      'rules': ['选择自己弃牌区中的1张基本能量，附着于备战宝可梦身上。'],
                      'trainer_type': 'Supporter'},
 'svl-ensw': {'name': '能量输送',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['选择自己牌库中的1张基本能量，在给对手看过之后，加入手牌。并重洗牌库。'],
              'trainer_type': 'Item'},
 'svl-trks': {'name': '健行鞋',
              'supertype': 'Trainer',
              'subtypes': ['Item'],
              'rules': ['查看自己牌库上方1张卡牌，将那张卡牌加入手牌。或者，将那张卡牌放于弃牌区，从自己牌库上方抽取1张卡牌。'],
              'trainer_type': 'Item'},
 'svl-vitb': {'name': '活力头带',
              'supertype': 'Trainer',
              'subtypes': ['Tool'],
              'rules': ['身上放有这张卡牌的宝可梦所使用的招式，给对手的战斗宝可梦造成的伤害「+10」。'],
              'trainer_type': 'Tool'},
 'svl-zinn': {'name': '希嘉娜的决心',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['这张卡牌，只有将自己的2张手牌放于弃牌区后才可使用。', '从自己的牌库上方抽取与对手场上宝可梦数量相同张数的卡牌。'],
              'trainer_type': 'Supporter'},
 'svg-chef': {'name': '西餐厨师',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['回复自己的战斗宝可梦「70」点HP。'],
              'trainer_type': 'Supporter'},
 'svg-beri': {'name': '贝里菈',
              'supertype': 'Trainer',
              'subtypes': ['Supporter'],
              'rules': ['从自己的牌库上方抽取卡牌，直到自己的手牌张数比对手的手牌张数多1张为止。'],
              'trainer_type': 'Supporter'},
 'svg2-hamm': {'name': '粉碎之锤',
               'supertype': 'Trainer',
               'subtypes': ['Item'],
               'rules': ['抛掷1次硬币如果为正面，则选择对手场上宝可梦身上附着的1个能量，放于弃牌区。'],
               'trainer_type': 'Item'},
 'svg2-exps': {'name': '学习装置',
               'supertype': 'Trainer',
               'subtypes': ['Tool'],
               'rules': ['每当自己的战斗宝可梦，受到对手宝可梦的招式的伤害而昏厥时，可选择该战斗宝可梦身上附着的1张基本能量，转附于身上放有这张卡牌的宝可梦身上。'],
               'trainer_type': 'Tool'},
 'svg2-gard': {'name': '菜种的活力',
               'supertype': 'Trainer',
               'subtypes': ['Supporter'],
               'rules': ['从自己牌库上方抽取2张卡牌。然后，选择自己手牌中最多2张G能量，附着于1只备战宝可梦身上。'],
               'trainer_type': 'Supporter'}}
