"""Compatibility facade for VM primitive command modules.

New code should import concrete command groups from the focused
``primitives_*`` modules. This module keeps older imports stable while the VM
compiler and runtime finish migrating away from the historical giant primitive
module.
"""
from __future__ import annotations

from engine.commands.primitives_combat import (
    _command_result_from_action_result,
    _attack_context_for_opponent_active,
    _consume_effect_damage_prevention,
    _check_bench_protection,
    _discard_pokemon_for_effect,
    _award_prizes_for_effect_ko,
    _set_promotion_or_game_over,
    _handle_effect_ko_if_needed,
    _queue_or_apply_opponent_active_damage,
    DealDamage,
    DealDamageFormula,
    SetAttackDamageFormula,
    ConditionalDamageHeal,
    DamageAndSelfHeal,
    ConditionalDamageBonus,
    DiscardHandThenDamage,
    DiscardEnergyThenDamage,
    MillThenDamage,
    BenchDamage,
    ChooseDamageTarget,
    PlaceCountersThenSelfDiscard,
)
from engine.commands.primitives_status import ApplyStatus
from engine.commands.primitives_draw import (
    DrawCards,
    DrawUntil,
    DrawUntilMore,
    ShuffleThenDrawCards,
    Judge,
)
from engine.commands.primitives_recovery import (
    RecoverFromDiscard,
    HandToBottomThenDraw,
    HandToBottomDrawUntil,
    ZinniaResolve,
    AbilityDiscardRevive,
    EvolveSkipStage,
)
from engine.commands.primitives_search import (
    SearchCards,
    LookTopDeck,
    LookTopAttachEnergy,
    SearchItemAndTool,
    TrekkingShoes,
    ConditionalSearchExtra,
    SearchAnyAndSwitch,
)
from engine.commands.primitives_energy import (
    DrawAndAttachEnergy,
    EnergyAttach,
    AttachEnergyFromDiscard,
    EnergyRelocate,
)
from engine.commands.primitives_coin import (
    CoinFlipSpecial,
    CoinFlipEnergyDiscard,
    Conditional,
    FlipCoin,
    _branch_payload,
    _build_branch_command,
)
from engine.commands.primitives_board import (
    _energy_card_matches,
    DiscardEnergy,
    HealDamage,
    ChooseHealDamage,
    SwitchPokemon,
    SearchZone,
    DiscardCards,
    DiscardThenDrawCards,
)
from engine.commands.primitives_attack import (
    AttackFail,
    SetAttackFlags,
    ReturnToHand,
    SetPrevention,
    DazzlingBeam,
    AttackLockBasic,
    OutgoingDamageReduction,
    SelfAttackLock,
    RegisterModifier,
    RegisterToolModifier,
)

__all__ = [
    "_command_result_from_action_result",
    "_attack_context_for_opponent_active",
    "_consume_effect_damage_prevention",
    "_check_bench_protection",
    "_discard_pokemon_for_effect",
    "_award_prizes_for_effect_ko",
    "_set_promotion_or_game_over",
    "_handle_effect_ko_if_needed",
    "_queue_or_apply_opponent_active_damage",
    "_branch_payload",
    "_build_branch_command",
    "_energy_card_matches",
    "DealDamage",
    "DealDamageFormula",
    "SetAttackDamageFormula",
    "ConditionalDamageHeal",
    "DamageAndSelfHeal",
    "ConditionalDamageBonus",
    "DiscardHandThenDamage",
    "DiscardEnergyThenDamage",
    "MillThenDamage",
    "BenchDamage",
    "ChooseDamageTarget",
    "PlaceCountersThenSelfDiscard",
    "ApplyStatus",
    "DrawCards",
    "DrawUntil",
    "DrawUntilMore",
    "ShuffleThenDrawCards",
    "Judge",
    "RecoverFromDiscard",
    "HandToBottomThenDraw",
    "HandToBottomDrawUntil",
    "ZinniaResolve",
    "AbilityDiscardRevive",
    "EvolveSkipStage",
    "SearchCards",
    "LookTopDeck",
    "LookTopAttachEnergy",
    "SearchItemAndTool",
    "TrekkingShoes",
    "ConditionalSearchExtra",
    "SearchAnyAndSwitch",
    "DrawAndAttachEnergy",
    "EnergyAttach",
    "AttachEnergyFromDiscard",
    "EnergyRelocate",
    "CoinFlipSpecial",
    "CoinFlipEnergyDiscard",
    "Conditional",
    "FlipCoin",
    "DiscardEnergy",
    "HealDamage",
    "ChooseHealDamage",
    "SwitchPokemon",
    "SearchZone",
    "DiscardCards",
    "DiscardThenDrawCards",
    "AttackFail",
    "SetAttackFlags",
    "ReturnToHand",
    "SetPrevention",
    "DazzlingBeam",
    "AttackLockBasic",
    "OutgoingDamageReduction",
    "SelfAttackLock",
    "RegisterModifier",
    "RegisterToolModifier",
]
