#!/usr/bin/env python

import os
import sys
import json
from SCons.Script import Default, Environment


env = Environment(ENV=os.environ)
env.Append(CPPPATH=["src"])
if sys.platform == "win32":
    env.Append(CXXFLAGS=["/EHsc", "/std:c++17", "/O2", "/utf-8"])
else:
    env.Append(CXXFLAGS=["-std=c++17", "-O2", "-pthread"])
    env.Append(LINKFLAGS=["-pthread"])

with open("source_manifest.json", encoding="utf-8") as handle:
    source_manifest = json.load(handle)
source_names = source_manifest["runtime"] + source_manifest["product_only"]

core_objects = [
    env.Object(
        os.path.join("build", "core", name),
        os.path.join("src", name + ".cpp"),
    )[0]
    for filename in source_names
    for name in (os.path.splitext(filename)[0],)
]
test_object = env.Object(
    os.path.join("build", "tests", "ptcg_rules_session_test"),
    "tests/ptcg_rules_session_test.cpp",
)[0]
program = env.Program(
    os.path.join("bin", "ptcg_core_tests"),
    source=[
        test_object,
        *core_objects,
    ],
)
env.NoCache(program)
Default(program)
