"""Core Pokemon TCG rule constants used by the engine."""

DECK_SIZE = 60
HAND_SIZE_INITIAL = 7
MAX_BENCH_SIZE = 5
PRIZE_CARDS = 6
MAX_COPIES_PER_CARD = 4

DAMAGE_PER_COUNTER = 10
COIN_FLIP_THRESHOLD = 0.5
TOOL_HP_BOOST = 50
