#!/usr/bin/env python

import os
from SCons.Script import ARGUMENTS, Default, Glob, SConscript


def _consume_path_argument(name, default):
    # These arguments belong to this extension, not godot-cpp's nested
    # SConstruct. Remove them before delegation so SCons does not report them
    # as unknown variables after they have already been consumed here.
    return os.path.abspath(ARGUMENTS.pop(name, default))


godot_cpp_dir = _consume_path_argument("godot_cpp_dir", "godot-cpp")
ort_root = _consume_path_argument("ort_root", "onnxruntime")
project_root = _consume_path_argument("project_root", "../..")

env = SConscript(os.path.join(godot_cpp_dir, "SConstruct"))
env.Append(CPPPATH=[
    "src",
    os.path.join(ort_root, "windows-x64", "include"),
])

if env["platform"] == "windows":
    env.Append(
        LIBPATH=[os.path.join(ort_root, "windows-x64", "lib")],
        LIBS=["onnxruntime"],
        CXXFLAGS=["/EHsc"],
    )
elif env["platform"] == "android":
    env.Append(
        LIBPATH=[os.path.join(ort_root, "android", "jni", "arm64-v8a")],
        LIBS=["onnxruntime"],
        CXXFLAGS=["-fexceptions"],
        LINKFLAGS=["-Wl,-rpath,$ORIGIN"],
    )

sources = Glob("src/*.cpp")
output = os.path.join(
    project_root,
    "bin",
    env["platform"],
    "libpokemon_ai{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
)
library = env.SharedLibrary(output, source=sources)
env.NoCache(library)
Default(library)
