"""Built-in card effects: colorless."""

EFFECTS = {'svi-sqwk': {'attacks': {'呼朋引伴': {'effects': [{'effect_type': 'search',
                                                'params': {'from_zone': 'deck',
                                                           'filter': 'basic_pokemon',
                                                           'destination': 'bench',
                                                           'reveal': True,
                                                           'count': 2,
                                                           'min_select': 0}}]},
                          '飞翔': {'effects': [{'effect_type': 'coin_flip',
                                              'params': {'on_heads': [{'effect_type': 'damage',
                                                                       'params': {'amount': 60,
                                                                                  'target': 'opponent_active'}},
                                                                      {'effect_type': 'prevent_all',
                                                                       'params': {}}],
                                                         'on_tails': [{'effect_type': 'attack_fail',
                                                                       'params': {}}]}}]}}},
 'svi-aipo': {'attacks': {'骗取': {'effects': [{'effect_type': 'draw',
                                              'params': {'amount': 1, 'player': 'self'}}]},
                          '掌击': {'effects': []}}},
 'svi-ambi': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                              'params': {'amount': 2, 'player': 'self'}}]},
                          '长手抛掷': {'effects': [{'effect_type': 'damage_per_hand_size',
                                                'params': {'per': 20}}]}}},
 'svi-stan': {'attacks': {'后踢': {'effects': []},
                          '疯狂俯冲': {'effects': [{'effect_type': 'damage_per_energy',
                                                'params': {'base': 0,
                                                           'per_energy': 30,
                                                           'count_from': 'opponent_active',
                                                           'target': 'opponent_active'}}]}}},
 'svi-skwv': {'attacks': {'啃咬': {'effects': []}}},
 'svi-gree': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                              'params': {'amount': 2, 'player': 'self'}}]},
                          '倾倒一空': {'effects': [{'effect_type': 'discard_hand_conditional_bonus',
                                                'params': {'threshold': 5,
                                                           'base_damage': 60,
                                                           'bonus': 150}}]}}},
 'svi-inde': {'attacks': {'招来': {'effects': [{'effect_type': 'draw',
                                              'params': {'amount': 2, 'player': 'self'}}]},
                          '妙手强念': {'effects': [{'effect_type': 'damage_per_hand_size',
                                                'params': {'per': 10}}]}}},
 'svi-tand': {'attacks': {'紧贴': {'effects': []}, '踢飞': {'effects': []}}},
 'svi-maus': {'abilities': {'团结一致': {'trigger': 'on_damaged',
                                     'effects': [{'effect_type': 'reactive_thorns',
                                                  'params': {'filter_names': ['一对鼠', '一家鼠ex', '一家鼠'],
                                                             'per_pokemon': 3}}]}},
              'attacks': {'贪婪门牙': {'effects': [{'effect_type': 'draw',
                                                'params': {'amount': 2, 'player': 'self'}}]}}},
 'svi-flam': {'attacks': {'振翅': {'effects': []},
                          '俯冲': {'effects': [{'effect_type': 'damage_counter_self',
                                              'params': {'amount': 20}}]}}},
 'svl-chat': {'attacks': {'循环抽取': {'effects': [{'effect_type': 'discard_then_draw',
                                                'params': {'discard_amount': 1, 'draw_amount': 2}}]},
                          '振翅': {'effects': []}}},
 'svf-farf': {'attacks': {'背来': {'effects': [{'effect_type': 'draw',
                                              'params': {'amount': 2, 'player': 'self'}}]},
                          '甩葱殴打': {'effects': []}}},
 'svf-hawl': {'attacks': {'展示姿态': {'effects': [{'effect_type': 'attach_from_discard',
                                                'params': {'amount': 2,
                                                           'energy_type': 'basic',
                                                           'target': 'bench',
                                                           'min_select': 0}}]},
                          '挥落': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                              'params': {'bonus': 30,
                                                         'condition': 'opponent_active_evolved'}}]}}},
 'svg-swa': {'attacks': {'连续旋转': {'effects': [{'effect_type': 'coin_flip_until_tails',
                                               'params': {'per_head': 20}}]}}},
 'svg-milt': {'attacks': {'活泼冲撞': {'effects': [{'effect_type': 'conditional_damage_heal',
                                                'params': {'base': 60, 'bonus': 90}}]}}},
 'svg-cast': {'attacks': {'双重抽取': {'effects': [{'effect_type': 'draw', 'params': {'amount': 2}}]},
                          '暴风': {'effects': [{'effect_type': 'energy_relocate',
                                              'params': {'amount': 1,
                                                         'from_self': True,
                                                         'energy_type': 'basic_energy'}}]}}}}
