"""Built-in card effects: fighting."""

EFFECTS = {'svf-rio': {'attacks': {'重拳': {'effects': []},
                         '突击': {'effects': [{'effect_type': 'damage_counter_self',
                                             'params': {'amount': 20,
                                                        'damage_kind': 'self_damage'}}]}}},
 'svf-luca': {'abilities': {'旺盛斗气': {'trigger': '',
                                     'effects': [{'effect_type': 'damage_counter_self',
                                                  'params': {'amount': 20}},
                                                 {'effect_type': 'energy_attach',
                                                  'params': {'amount': 1,
                                                             'from_zone': 'deck',
                                                             'filter': 'fighting',
                                                             'to': 'self'}}]}},
              'attacks': {'连续波导弹': {'effects': [{'effect_type': 'discard_fighting_energy_damage',
                                                 'params': {'base': 10, 'per_energy': 60}}]}}},
 'svf-klea': {'attacks': {'大树切割': {'effects': [{'effect_type': 'coin_flip_double_ko', 'params': {}}]},
                          '暴走冲撞': {'effects': [{'effect_type': 'damage_counter_self',
                                                'params': {'amount': 30,
                                                           'damage_kind': 'self_damage'}}]}}},
 'svf-pass': {'attacks': {'辅助传递': {'effects': [{'effect_type': 'energy_relocate',
                                                'params': {'amount': 1, 'from_self': True}}]}}},
 'svf-terr': {'attacks': {'岩窟冲撞': {'effects': [{'effect_type': 'prevent_damage', 'params': {}},
                                               {'effect_type': 'self_attack_lock',
                                                'params': {'attack_name': '岩窟冲撞',
                                                           'scope': 'player'}}]}}}}
