"""Built-in card effects: fire."""

EFFECTS = {'svi-chim': {'attacks': {'火花': {'effects': [{'effect_type': 'energy_discard',
                                              'params': {'amount': 1, 'from': 'self', 'filter': 'any'}}]}}},
 'svi-monf': {'attacks': {'火焰': {'effects': []},
                          '喷射火焰': {'effects': [{'effect_type': 'energy_discard',
                                                'params': {'amount': 1, 'from': 'self', 'filter': 'any'}}]}}},
 'svi-infr': {'attacks': {'螺旋业火': {'effects': [{'effect_type': 'mill_and_damage_per_energy',
                                                'params': {'mill_count': 5, 'damage_per': 80}}]},
                          '燃烧踢': {'effects': [{'effect_type': 'energy_discard',
                                               'params': {'amount': 99, 'from': 'self', 'filter': 'any'}}]}}},
 'svi-ente': {'abilities': {'压迫感': {'trigger': 'passive',
                                    'text': '只要这只宝可梦在战斗场上，对手战斗宝可梦使用的招式伤害「-20」。',
                                    'effects': [{'effect_type': 'aura_damage_reduction',
                                                 'params': {'reduction': 20}}]}},
              'attacks': {'火焰之球': {'effects': [{'effect_type': 'damage_per_self_energy',
                                                'params': {'base': 60,
                                                           'per_energy': 20,
                                                           'energy_filter': 'fire'}}]}}},
 'svi-hrot': {'attacks': {'高温冲撞': {'effects': [{'effect_type': 'damage_counter_self',
                                                'params': {'amount': 40}}]}}},
 'svi-chiy': {'attacks': {'闪焰生成': {'effects': [{'effect_type': 'attach_from_discard',
                                                'params': {'amount': 2,
                                                           'energy_type': 'fire',
                                                           'target': 'self_or_bench',
                                                           'min_select': 0}}]},
                          '嫉妒业火': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                                'params': {'bonus': 90,
                                                           'condition': 'ko_by_attack_last_turn'}}]}}}}
