"""Built-in card effects: grass."""

EFFECTS = {'svf-scyt': {'attacks': {'高速镰刀': {'effects': []}}},
 'svg2-turt': {'attacks': {'咬住': {'effects': []}, '鲁莽头击': {'effects': []}}},
 'svg2-grot': {'abilities': {'日光甲壳': {'trigger': 'on_turn',
                                      'effects': [{'effect_type': 'search',
                                                   'params': {'from_zone': 'deck',
                                                              'filter': 'grass_pokemon',
                                                              'destination': 'hand',
                                                              'reveal': True,
                                                              'count': 1}}]}},
               'attacks': {'飞叶快刀': {'effects': []}}},
 'svg2-tort': {'attacks': {'进化压制': {'effects': [{'effect_type': 'damage_per_evolved',
                                                 'params': {'per_evolved': 50}}]},
                           '头突': {'effects': []}}},
 'svg2-shro': {'attacks': {'吸取': {'effects': [{'effect_type': 'damage_and_self_heal',
                                               'params': {'damage': 10, 'heal': 10}}]}}},
 'svg2-brel': {'attacks': {'音速直击': {'effects': []}}},
 'svg2-zaru': {'attacks': {'唤群之歌': {'effects': [{'effect_type': 'conditional_search_extra',
                                                 'params': {'filter': 'grass_pokemon',
                                                            'max_count': 3,
                                                            'default_count': 1}}]},
                           '反复鞭挞': {'effects': [{'effect_type': 'damage_per_self_energy_type',
                                                 'params': {'base': 60,
                                                            'per_energy': 20,
                                                            'energy_type': 'Grass'}}]}}}}
