"""Built-in card effects: lightning."""

EFFECTS = {'svl-pikaex': {'attacks': {'皮卡拳': {'effects': []},
                            '强劲伏特': {'effects': [{'effect_type': 'coin_flip',
                                                  'params': {'on_heads': [],
                                                             'on_tails': [{'effect_type': 'energy_discard',
                                                                           'params': {'amount': 99,
                                                                                      'from': 'self',
                                                                                      'filter': 'any'}}]}}]}}},
 'svl-chin': {'attacks': {'电球': {'effects': []}}},
 'svl-lant': {'attacks': {'炫目光束': {'effects': [{'effect_type': 'dazzling_beam',
                                                'params': {'target': 'opponent_active'}}]},
                          '电球': {'effects': []}}},
 'svl-mare2': {'attacks': {'后踢': {'effects': []}, '电球': {'effects': []}}},
 'svl-flaa2': {'abilities': {'电气发电机': {'trigger': '',
                                       'effects': [{'effect_type': 'attach_from_discard',
                                                    'params': {'amount': 1,
                                                               'energy_type': 'lightning',
                                                               'target': 'bench'}}]}},
               'attacks': {'电球': {'effects': []}}},
 'svl-emol': {'attacks': {'电击': {'effects': [{'effect_type': 'coin_flip',
                                              'params': {'on_heads': [{'effect_type': 'status',
                                                                       'params': {'status': 'paralyzed',
                                                                                  'target': 'opponent_active'}}],
                                                         'on_tails': []}}]}}},
 'svl-thun': {'attacks': {'辅助电光': {'effects': [{'effect_type': 'energy_attach',
                                                'params': {'amount': 1,
                                                           'from_zone': 'hand',
                                                           'filter': 'lightning',
                                                           'to': 'bench',
                                                           'optional': True}}]},
                          '打雷': {'effects': [{'effect_type': 'damage_counter_self',
                                              'params': {'amount': 30,
                                                         'damage_kind': 'self_damage'}}]}}},
 'svl-zera': {'attacks': {'疯狂伏特': {'effects': [{'effect_type': 'damage_counter_self',
                                                'params': {'amount': 20,
                                                           'damage_kind': 'self_damage'}}]}}}}
