"""Built-in card effects: psychic."""

EFFECTS = {'sv1-104': {'attacks': {'啃咬': {'effects': []}, '幽魂射击': {'effects': []}}},
 'sv1-106': {'attacks': {'扫墓': {'effects': [{'effect_type': 'damage_per_discard_psychic',
                                             'params': {'base': 80, 'per_card': 10}}]}}},
 'sv1-107': {'attacks': {'三连突刺': {'effects': [{'effect_type': 'coin_flip_triple',
                                               'params': {'flips': 3, 'damage_per_head': 10}}]}}},
 'sv1-108': {'abilities': {'以太感知': {'trigger': '',
                                    'effects': [{'effect_type': 'energy_attach',
                                                 'params': {'amount': 1,
                                                            'from_zone': 'hand',
                                                            'filter': 'psychic',
                                                            'to': 'bench'}},
                                                {'effect_type': 'draw',
                                                 'params': {'amount': 2, 'player': 'self'}}]}},
             'attacks': {'超念力': {'effects': []}}},
 'sv1-109': {'attacks': {'循环抽取': {'effects': [{'effect_type': 'discard_then_draw',
                                               'params': {'discard_amount': 1, 'draw_amount': 3}}]},
                         '月亮强念': {'effects': [{'effect_type': 'damage_per_self_energy',
                                               'params': {'base': 30,
                                                          'per_energy': 30,
                                                          'energy_filter': 'psychic'}}]}}},
 'sv1-110': {'abilities': {'薄雾飘浮': {'trigger': 'passive',
                                    'text': '如果这只宝可梦身上附着了超能量的话，则这只宝可梦撤退所需能量全部消除。',
                                    'effects': [{'effect_type': 'conditional_zero_retreat',
                                                 'params': {'energy_type': 'psychic'}}]}},
             'attacks': {'念动弹': {'effects': []}}},
 'sv1-111': {'attacks': {'滑翔': {'effects': []},
                         '洁净光芒': {'effects': [{'effect_type': 'energy_discard',
                                               'params': {'amount': 3, 'from': 'self', 'filter': 'any'}}]}}},
 'sv1-112': {'attacks': {'精神拳': {'effects': []},
                         '基因螺旋': {'effects': [{'effect_type': 'energy_relocate',
                                               'params': {'amount': 99, 'from_self': True}}]}}},
 'sv1-113': {'attacks': {'新月生长': {'effects': [{'effect_type': 'energy_attach',
                                               'params': {'amount': 1,
                                                          'from_zone': 'deck',
                                                          'filter': 'psychic',
                                                          'to': 'any',
                                                          'going_second_bonus': 3}}]},
                         '光子镭射': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                               'params': {'bonus': 90, 'condition': 'field_energy_ge_5'}}]}}},
 'sv1-114': {'attacks': {'小使者': {'effects': [{'effect_type': 'search',
                                              'params': {'from_zone': 'deck',
                                                         'filter': 'basic_energy',
                                                         'destination': 'hand',
                                                         'count': 2,
                                                         'min_select': 0,
                                                         'reveal': True}}]},
                         '旋转折返': {'effects': [{'effect_type': 'switch_self',
                                               'params': {'optional': True}}]}}}}
