"""Built-in card effects: trainer."""

EFFECTS = {'sv2-young': {'trainer_effect': {'effect_type': 'shuffle_draw',
                                  'params': {'shuffle_hand': True, 'draw': 5, 'affect': 'self_only'}}},
 'sv2-cand': {'trainer_effect': {'effect_type': 'look_top_deck',
                                 'params': {'count': 7,
                                            'take': 99,
                                            'shuffle_rest': True,
                                            'min_select': 0,
                                            'filter': 'water_pokemon_and_energy'}}},
 'sv2-catch': {'trainer_effect': {'effect_type': 'coin_flip',
                                  'params': {'on_heads': [{'effect_type': 'switch_opponent',
                                                           'params': {'you_choose': True}}],
                                             'on_tails': []}}},
 'sv1-189': {'trainer_effect': {'effect_type': 'discard_draw', 'params': {'discard_hand': True, 'draw': 7}}},
 'sv1-176': {'trainer_effect': {'effect_type': 'judge', 'params': {'draw': 4}}},
 'sv1-180': {'trainer_effect': {'effect_type': 'draw', 'params': {'amount': 3, 'player': 'self'}}},
 'sv1-150': {'trainer_effect': {'effect_type': 'switch_self', 'params': {}}},
 'sv1-151': {'trainer_effect': {'effect_type': 'search',
                                'params': {'from_zone': 'deck',
                                           'filter': 'basic_pokemon',
                                           'destination': 'bench',
                                           'reveal': True,
                                           'count': 1}}},
 'sv1-152': {'trainer_effect': {'effect_type': 'evolve_skip_stage', 'params': {'skip_to': 'stage2'}}},
 'sv1-153': {'trainer_effect': {'effect_type': 'conditional',
                                'params': {'cost': {'effect_type': 'discard',
                                                    'params': {'amount': 2, 'from': 'hand'}},
                                           'on_pay': {'effect_type': 'search',
                                                      'params': {'from_zone': 'deck',
                                                                 'filter': 'pokemon',
                                                                 'destination': 'hand',
                                                                 'reveal': True,
                                                                 'count': 1}}}}},
 'sv3-134': {'trainer_effect': {'effect_type': 'shuffle_from_discard',
                                'params': {'count': 3, 'filter': 'pokemon_and_energy'}}},
 'sv1-170': {'trainer_effect': {'effect_type': 'look_top_deck',
                                'params': {'count': 5,
                                           'take': 2,
                                           'shuffle_rest': True,
                                           'filter': 'lightning_energy',
                                           'destination': 'bench_energy',
                                           'target_pokemon_type': 'Lightning',
                                           'min_select': 0}}},
 'sv1-171': {'trainer_effect': {'effect_type': 'search',
                                'params': {'from_zone': 'discard',
                                           'filter': 'basic_energy',
                                           'destination': 'hand',
                                           'count': 2,
                                           'min_select': 0,
                                           'reveal': True}}},
 'svi-mela': {'trainer_effect': {'effect_type': 'conditional',
                                 'params': {'condition': 'ko_last_opponent_turn',
                                            'cost': None,
                                            'on_pay': [{'effect_type': 'attach_from_discard',
                                                        'params': {'amount': 1,
                                                                   'energy_type': 'fire',
                                                                   'target': 'self_or_bench'}},
                                                       {'effect_type': 'draw_until',
                                                        'params': {'target_hand_size': 6}}]}}},
 'svi-erec': {'trainer_effect': {'effect_type': 'shuffle_from_discard',
                                 'params': {'count': 5, 'filter': 'basic_energy'}}},
 'svi-enst': {'trainer_effect': {'effect_type': 'look_top_deck',
                                 'params': {'count': 7,
                                            'take': 1,
                                            'filter': 'energy',
                                            'destination': 'hand',
                                            'shuffle_rest': True}}},
 'svi-nemb': {'trainer_effect': {'effect_type': 'search',
                                 'params': {'from_zone': 'discard',
                                            'filter': 'any',
                                            'filter_name': '妮莫',
                                            'destination': 'hand',
                                            'reveal': True,
                                            'count': 2,
                                            'min_select': 0}}},
 'svi-cait': {'trainer_effect': {'effect_type': 'hand_to_bottom_draw', 'params': {}}},
 'svi-popp': {'trainer_effect': {'effect_type': 'energy_relocate',
                                 'params': {'amount': 2, 'min_select': 0, 'same_target': True}}},
 'sv1-201': {'trainer_effect': {'effect_type': 'tool', 'params': {'effect': 'damage_boost_when_behind'}}},
 'sv1-202': {'trainer_effect': {'effect_type': 'tool', 'params': {'effect': 'hp_boost_basic'}}},
 'sv1-203': {'trainer_effect': {'effect_type': 'clara', 'params': {'pokemon_count': 2, 'energy_count': 2}}},
 'sv1-204': {'trainer_effect': {'effect_type': 'arven', 'params': {}}},
 'svm-marnie-pride': {'trainer_effect': {'effect_type': 'attach_from_discard',
                                         'params': {'amount': 1,
                                                    'energy_type': 'basic_energy',
                                                    'target': 'bench',
                                                    'select_source': True}}},
 'svl-ensw': {'trainer_effect': {'effect_type': 'search',
                                 'params': {'from_zone': 'deck',
                                            'filter': 'basic_energy',
                                            'destination': 'hand',
                                            'count': 1,
                                            'reveal': True}}},
 'svl-trks': {'trainer_effect': {'effect_type': 'trekking_shoes', 'params': {}}},
 'svl-vitb': {'trainer_effect': {'effect_type': 'tool', 'params': {'effect': 'damage_boost_10'}}},
 'svl-zinn': {'trainer_effect': {'effect_type': 'zinnia_resolve', 'params': {}}},
 'svf-potion': {'trainer_effect': {'effect_type': 'potion_heal', 'params': {'amount': 30}}},
 'svf-ensw2': {'trainer_effect': {'effect_type': 'energy_relocate',
                                  'params': {'amount': 1, 'energy_type': 'basic_energy'}}},
 'svf-houb': {'trainer_effect': {'effect_type': 'houb', 'params': {'target_hand_size': 5}}},
 'svg-chef': {'trainer_effect': {'effect_type': 'heal', 'params': {'amount': 70, 'target': 'self'}}},
 'svg-beri': {'trainer_effect': {'effect_type': 'draw_until_more', 'params': {}}},
 'svg2-hamm': {'trainer_effect': {'effect_type': 'coin_flip_energy_discard', 'params': {}}},
 'svg2-exps': {'trainer_effect': {'effect_type': 'tool_exp_share', 'params': {}}},
 'svg2-gard': {'trainer_effect': {'effect_type': 'draw_and_attach_energy',
                                  'params': {'energy_count': 2,
                                             'energy_type': 'Grass',
                                             'min_select': 0}}}}
