"""Built-in card effects: water."""

EFFECTS = {'sv1-49': {'attacks': {'愤怒冷冻': {'effects': [{'effect_type': 'conditional_status',
                                              'params': {'status': 'paralyzed',
                                                         'target': 'opponent_active',
                                                         'condition': 'ko_by_attack_damage_last_turn'}}]}}},
 'sv2-grex': {'attacks': {'隐蔽手里剑': {'effects': [{'effect_type': 'any_pokemon_damage',
                                                 'params': {'amount': 40,
                                                            'player': 'opponent',
                                                            'bench_skips_type_matchups': True}}]},
                          '激流斩': {'effects': [{'effect_type': 'conditional_damage_bonus',
                                               'params': {'bonus': 120,
                                                          'condition': 'opponent_active_damaged'}}]}}},
 'sv2-keldeo': {'attacks': {'踢飞': {'effects': []},
                            '队列之力': {'effects': [{'effect_type': 'damage_plus_bench',
                                                  'params': {'base': 10,
                                                             'per_bench': 20,
                                                             'count_own_bench': True}}]}}},
 'sv2-glast': {'attacks': {'冻结': {'effects': [{'effect_type': 'attack_lock_basic',
                                               'params': {'target': 'opponent_active'}}]},
                           '疯狂冲撞': {'effects': [{'effect_type': 'damage_counter_self',
                                                 'params': {'amount': 30}}]}}},
 'sv2-tatsu': {'attacks': {'预先准备': {'effects': [{'effect_type': 'energy_attach',
                                                 'params': {'amount': 2,
                                                            'from_zone': 'deck',
                                                            'filter': 'water',
                                                            'to': 'self_basic',
                                                            'min_select': 0}}]},
                           '上弓折返': {'effects': [{'effect_type': 'return_to_hand', 'params': {}}]}}},
 'sv2-delib': {'attacks': {'双重抽取': {'effects': [{'effect_type': 'draw',
                                                 'params': {'amount': 2, 'player': 'self'}}]},
                           '冰之翼': {'effects': []}}},
 'sv2-staryu': {'attacks': {'高速星星': {'effects': [{'effect_type': 'attack_flags',
                                                  'params': {'ignore_weakness': True,
                                                             'ignore_resistance': True,
                                                             'ignore_defender_damage_effects': True}}]}}},
 'sv2-starm': {'abilities': {'神秘彗星': {'trigger': '',
                                      'effects': [{'effect_type': 'place_counters_and_self_discard',
                                                   'params': {'counters': 2, 'target': 'opponent_any'}}]}},
               'attacks': {'高速攻击': {'effects': []}}},
 'sv2-38': {'attacks': {'跳一下': {'effects': [{'effect_type': 'coin_flip',
                                             'params': {'on_heads': [],
                                                        'on_tails': [{'effect_type': 'attack_fail',
                                                                      'params': {}}]}}]}}},
 'sv2-39': {'attacks': {'折返瞬击': {'effects': [{'effect_type': 'switch_self', 'params': {'optional': True}}]}}},
 'svg-ceto': {'attacks': {'撞击': {'effects': []}}},
 'svg-ceti': {'attacks': {'头突': {'effects': []},
                          '扫除冲撞': {'effects': [{'effect_type': 'damage_self_penalty',
                                                'params': {'base': 200, 'per_counter': 20}}]}}},
 'svg2-empo': {'abilities': {'紧急上浮': {'trigger': 'on_turn',
                                      'effects': [{'effect_type': 'ability_discard_revive',
                                                   'params': {'card_id': 'svg2-empo'}}]}},
               'attacks': {'水之矢': {'effects': [{'effect_type': 'any_pokemon_damage',
                                                'params': {'amount': 60, 'bench_skips_type_matchups': True}}]}}}}
